# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Qiandao_face_Main.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class UIQiandaoFace(object):
    def setupUi(self, UIQiandaoFace):
        UIQiandaoFace.setObjectName("UIQiandaoFace")
        UIQiandaoFace.resize(1291, 651)
        UIQiandaoFace.setToolTipDuration(-1)
        UIQiandaoFace.setStyleSheet("background-color: rgb(232, 232, 232);")
        self.lb_toplabel = QtWidgets.QLabel(UIQiandaoFace)
        self.lb_toplabel.setGeometry(QtCore.QRect(440, 20, 401, 51))
        self.lb_toplabel.setStyleSheet("font: 75 28pt \"楷体\";")
        self.lb_toplabel.setTextFormat(QtCore.Qt.AutoText)
        self.lb_toplabel.setObjectName("lb_toplabel")
        self.GBstudent = QtWidgets.QGroupBox(UIQiandaoFace)
        self.GBstudent.setGeometry(QtCore.QRect(100, 70, 411, 541))
        self.GBstudent.setObjectName("GBstudent")
        self.tableView = QtWidgets.QTableView(self.GBstudent)
        self.tableView.setGeometry(QtCore.QRect(10, 30, 391, 501))
        self.tableView.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableView.setObjectName("tableView")
        self.groupBox = QtWidgets.QGroupBox(UIQiandaoFace)
        self.groupBox.setGeometry(QtCore.QRect(520, 70, 301, 541))
        self.groupBox.setObjectName("groupBox")
        self.lb_name = QtWidgets.QLabel(self.groupBox)
        self.lb_name.setGeometry(QtCore.QRect(20, 70, 81, 31))
        self.lb_name.setStyleSheet("font: 14pt \"宋体\";")
        self.lb_name.setObjectName("lb_name")
        self.lb_nameinfo = QtWidgets.QLabel(self.groupBox)
        self.lb_nameinfo.setGeometry(QtCore.QRect(120, 70, 131, 21))
        self.lb_nameinfo.setStyleSheet("background-color: rgb(152, 152, 152);\n"
"font: 14pt \"楷体\";")
        self.lb_nameinfo.setObjectName("lb_nameinfo")
        self.lb_date = QtWidgets.QLabel(self.groupBox)
        self.lb_date.setGeometry(QtCore.QRect(20, 220, 81, 20))
        self.lb_date.setStyleSheet("font: 14pt \"宋体\";")
        self.lb_date.setObjectName("lb_date")
        self.lb_dateinfo = QtWidgets.QLabel(self.groupBox)
        self.lb_dateinfo.setGeometry(QtCore.QRect(120, 220, 131, 21))
        self.lb_dateinfo.setStyleSheet("background-color: rgb(152, 152, 152);\n"
"font: 14pt \"楷体\";")
        self.lb_dateinfo.setObjectName("lb_dateinfo")
        self.lb_coach = QtWidgets.QLabel(self.groupBox)
        self.lb_coach.setGeometry(QtCore.QRect(20, 290, 81, 20))
        self.lb_coach.setStyleSheet("font: 14pt \"宋体\";")
        self.lb_coach.setObjectName("lb_coach")
        self.lb_rest = QtWidgets.QLabel(self.groupBox)
        self.lb_rest.setGeometry(QtCore.QRect(20, 360, 81, 20))
        self.lb_rest.setStyleSheet("font: 14pt \"宋体\";")
        self.lb_rest.setObjectName("lb_rest")
        self.lb_restinfo = QtWidgets.QLabel(self.groupBox)
        self.lb_restinfo.setGeometry(QtCore.QRect(120, 360, 131, 21))
        self.lb_restinfo.setStyleSheet("background-color: rgb(152, 152, 152);\n"
"font: 14pt \"楷体\";")
        self.lb_restinfo.setObjectName("lb_restinfo")
        self.lb_phone = QtWidgets.QLabel(self.groupBox)
        self.lb_phone.setGeometry(QtCore.QRect(20, 150, 81, 20))
        self.lb_phone.setStyleSheet("font: 14pt \"宋体\";")
        self.lb_phone.setObjectName("lb_phone")
        self.lb_phoneinfo = QtWidgets.QLabel(self.groupBox)
        self.lb_phoneinfo.setGeometry(QtCore.QRect(120, 150, 131, 21))
        self.lb_phoneinfo.setStyleSheet("background-color: rgb(152, 152, 152);\n"
"font: 14pt \"楷体\";")
        self.lb_phoneinfo.setObjectName("lb_phoneinfo")
        self.bt_qiandao_confrim = QtWidgets.QPushButton(self.groupBox)
        self.bt_qiandao_confrim.setGeometry(QtCore.QRect(40, 450, 201, 51))
        self.bt_qiandao_confrim.setObjectName("bt_qiandao_confrim")
        self.gb_coach = QtWidgets.QComboBox(self.groupBox)
        self.gb_coach.setGeometry(QtCore.QRect(130, 290, 111, 22))
        self.gb_coach.setObjectName("gb_coach")
        self.GB_qiandao = QtWidgets.QGroupBox(UIQiandaoFace)
        self.GB_qiandao.setGeometry(QtCore.QRect(830, 70, 371, 531))
        self.GB_qiandao.setStyleSheet("")
        self.GB_qiandao.setObjectName("GB_qiandao")
        self.lb_cam = QtWidgets.QLabel(self.GB_qiandao)
        self.lb_cam.setGeometry(QtCore.QRect(60, 40, 260, 346))
        self.lb_cam.setStyleSheet("background-color: rgb(172, 172, 172);")
        self.lb_cam.setText("")
        self.lb_cam.setObjectName("lb_cam")
        self.bt_opencam = QtWidgets.QPushButton(self.GB_qiandao)
        self.bt_opencam.setGeometry(QtCore.QRect(80, 400, 211, 51))
        self.bt_opencam.setObjectName("bt_opencam")
        self.bt_clear = QtWidgets.QPushButton(self.GB_qiandao)
        self.bt_clear.setGeometry(QtCore.QRect(80, 460, 211, 51))
        self.bt_clear.setObjectName("bt_clear")

        self.retranslateUi(UIQiandaoFace)
        QtCore.QMetaObject.connectSlotsByName(UIQiandaoFace)

    def retranslateUi(self, UIQiandaoFace):
        _translate = QtCore.QCoreApplication.translate
        UIQiandaoFace.setWindowTitle(_translate("UIQiandaoFace", "Form"))
        self.lb_toplabel.setText(_translate("UIQiandaoFace", "学 生 签 到 系 统 "))
        self.GBstudent.setTitle(_translate("UIQiandaoFace", "上课名单"))
        self.groupBox.setTitle(_translate("UIQiandaoFace", "学习信息"))
        self.lb_name.setText(_translate("UIQiandaoFace", "学生姓名"))
        self.lb_nameinfo.setText(_translate("UIQiandaoFace", "暂无"))
        self.lb_date.setText(_translate("UIQiandaoFace", "上课时间"))
        self.lb_dateinfo.setText(_translate("UIQiandaoFace", "暂无"))
        self.lb_coach.setText(_translate("UIQiandaoFace", "教练姓名"))
        self.lb_rest.setText(_translate("UIQiandaoFace", "剩余次数"))
        self.lb_restinfo.setText(_translate("UIQiandaoFace", "暂无"))
        self.lb_phone.setText(_translate("UIQiandaoFace", "电话号码"))
        self.lb_phoneinfo.setText(_translate("UIQiandaoFace", "暂无"))
        self.bt_qiandao_confrim.setText(_translate("UIQiandaoFace", "确认签到"))
        self.GB_qiandao.setTitle(_translate("UIQiandaoFace", "人脸签到"))
        self.bt_opencam.setText(_translate("UIQiandaoFace", "打开摄像头"))
        self.bt_clear.setText(_translate("UIQiandaoFace", "清空信息"))

