# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Qiandao_face_Main.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from Qiandao.ComboChecBox import ComboCheckBox

class Ui_UIQiandaoFace(object):
    def setupUi(self, UIQiandaoFace):
        UIQiandaoFace.setObjectName("UIQiandaoFace")
        UIQiandaoFace.resize(1291, 652)
        UIQiandaoFace.setToolTipDuration(-1)
        UIQiandaoFace.setStyleSheet("background-color: rgb(232, 232, 232);")
        self.lb_toplabel = QtWidgets.QLabel(UIQiandaoFace)
        self.lb_toplabel.setGeometry(QtCore.QRect(440, 20, 421, 51))
        self.lb_toplabel.setStyleSheet("font: 75 28pt \"楷体\";")
        self.lb_toplabel.setTextFormat(QtCore.Qt.AutoText)
        self.lb_toplabel.setObjectName("lb_toplabel")
        self.GBstudent = QtWidgets.QGroupBox(UIQiandaoFace)
        self.GBstudent.setGeometry(QtCore.QRect(30, 70, 521, 571))
        self.GBstudent.setObjectName("GBstudent")
        self.tv_student = QtWidgets.QTableView(self.GBstudent)
        self.tv_student.setGeometry(QtCore.QRect(10, 60, 491, 501))
        self.tv_student.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tv_student.setObjectName("tv_student")
        self.frame = QtWidgets.QFrame(self.GBstudent)
        self.frame.setGeometry(QtCore.QRect(30, 20, 481, 31))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(190, 10, 71, 16))
        self.label_2.setObjectName("label_2")
        self.dian = ['10点', '11点', '12点', '13点', '14点', '15点', '16点', '17点', '18点', '19点', '20点', '21点']
        self.cb_dian = ComboCheckBox(self.dian, self.frame)
        self.cb_dian.setGeometry(QtCore.QRect(270, 10, 111, 22))
        self.cb_dian.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.cb_dian.setObjectName("cb_dian")
        self.bt_search = QtWidgets.QPushButton(self.frame)
        self.bt_search.setGeometry(QtCore.QRect(400, 10, 61, 21))
        self.bt_search.setObjectName("bt_search")
        self.groupBox = QtWidgets.QGroupBox(UIQiandaoFace)
        self.groupBox.setGeometry(QtCore.QRect(570, 70, 301, 541))
        self.groupBox.setObjectName("groupBox")
        self.lb_name = QtWidgets.QLabel(self.groupBox)
        self.lb_name.setGeometry(QtCore.QRect(20, 70, 91, 31))
        self.lb_name.setStyleSheet("font: 14pt \"宋体\";")
        self.lb_name.setObjectName("lb_name")
        self.lb_date = QtWidgets.QLabel(self.groupBox)
        self.lb_date.setGeometry(QtCore.QRect(20, 220, 81, 20))
        self.lb_date.setStyleSheet("font: 14pt \"宋体\";")
        self.lb_date.setObjectName("lb_date")
        self.lb_coach = QtWidgets.QLabel(self.groupBox)
        self.lb_coach.setGeometry(QtCore.QRect(20, 290, 91, 20))
        self.lb_coach.setStyleSheet("font: 14pt \"宋体\";")
        self.lb_coach.setObjectName("lb_coach")
        self.lb_rest = QtWidgets.QLabel(self.groupBox)
        self.lb_rest.setGeometry(QtCore.QRect(20, 360, 101, 20))
        self.lb_rest.setStyleSheet("font: 14pt \"宋体\";")
        self.lb_rest.setObjectName("lb_rest")
        self.lb_phone = QtWidgets.QLabel(self.groupBox)
        self.lb_phone.setGeometry(QtCore.QRect(20, 150, 81, 20))
        self.lb_phone.setStyleSheet("font: 14pt \"宋体\";")
        self.lb_phone.setObjectName("lb_phone")
        self.bt_qiandao_confrim = QtWidgets.QPushButton(self.groupBox)
        self.bt_qiandao_confrim.setGeometry(QtCore.QRect(40, 450, 201, 51))
        self.bt_qiandao_confrim.setObjectName("bt_qiandao_confrim")
        self.cb_coach = QtWidgets.QComboBox(self.groupBox)
        self.cb_coach.setGeometry(QtCore.QRect(140, 290, 111, 22))
        self.cb_coach.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.cb_coach.setObjectName("cb_coach")
        self.et_name = QtWidgets.QLineEdit(self.groupBox)
        self.et_name.setGeometry(QtCore.QRect(130, 80, 131, 20))
        self.et_name.setObjectName("et_name")
        self.et_cishu = QtWidgets.QLineEdit(self.groupBox)
        self.et_cishu.setGeometry(QtCore.QRect(130, 360, 131, 20))
        self.et_cishu.setObjectName("et_cishu")
        self.et_phone = QtWidgets.QLineEdit(self.groupBox)
        self.et_phone.setGeometry(QtCore.QRect(130, 150, 131, 20))
        self.et_phone.setObjectName("et_phone")
        self.et_classtime = QtWidgets.QLineEdit(self.groupBox)
        self.et_classtime.setGeometry(QtCore.QRect(130, 220, 131, 20))
        self.et_classtime.setObjectName("et_classtime")
        self.GB_qiandao = QtWidgets.QGroupBox(UIQiandaoFace)
        self.GB_qiandao.setGeometry(QtCore.QRect(890, 70, 341, 531))
        self.GB_qiandao.setStyleSheet("")
        self.GB_qiandao.setObjectName("GB_qiandao")
        self.lb_cam = QtWidgets.QLabel(self.GB_qiandao)
        self.lb_cam.setGeometry(QtCore.QRect(30, 30, 260, 346))
        self.lb_cam.setStyleSheet("background-color: rgb(172, 172, 172);")
        self.lb_cam.setText("")
        self.lb_cam.setObjectName("lb_cam")
        self.bt_opencam = QtWidgets.QPushButton(self.GB_qiandao)
        self.bt_opencam.setGeometry(QtCore.QRect(60, 400, 211, 51))
        self.bt_opencam.setObjectName("bt_opencam")
        self.bt_clear = QtWidgets.QPushButton(self.GB_qiandao)
        self.bt_clear.setGeometry(QtCore.QRect(60, 460, 211, 51))
        self.bt_clear.setObjectName("bt_clear")
        self.lb_time = QtWidgets.QLabel(UIQiandaoFace)
        self.lb_time.setGeometry(QtCore.QRect(40, 30, 341, 16))
        self.lb_time.setObjectName("lb_time")

        self.retranslateUi(UIQiandaoFace)
        QtCore.QMetaObject.connectSlotsByName(UIQiandaoFace)

    def retranslateUi(self, UIQiandaoFace):
        _translate = QtCore.QCoreApplication.translate
        UIQiandaoFace.setWindowTitle(_translate("UIQiandaoFace", "Form"))
        self.lb_toplabel.setText(_translate("UIQiandaoFace", "学 生 签 到 系 统 "))
        self.GBstudent.setTitle(_translate("UIQiandaoFace", "上课名单"))
        self.label_2.setText(_translate("UIQiandaoFace", "选择课时"))
        self.bt_search.setText(_translate("UIQiandaoFace", "查询"))
        self.groupBox.setTitle(_translate("UIQiandaoFace", "学习信息"))
        self.lb_name.setText(_translate("UIQiandaoFace", "学生姓名"))
        self.lb_date.setText(_translate("UIQiandaoFace", "上课时间"))
        self.lb_coach.setText(_translate("UIQiandaoFace", "教练姓名"))
        self.lb_rest.setText(_translate("UIQiandaoFace", "剩余次数"))
        self.lb_phone.setText(_translate("UIQiandaoFace", "电话号码"))
        self.bt_qiandao_confrim.setText(_translate("UIQiandaoFace", "确认签到"))
        self.GB_qiandao.setTitle(_translate("UIQiandaoFace", "人脸签到"))
        self.bt_opencam.setText(_translate("UIQiandaoFace", "打开摄像头"))
        self.bt_clear.setText(_translate("UIQiandaoFace", "清空信息"))
        self.lb_time.setText(_translate("UIQiandaoFace", "当前时间"))

