# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NewMember.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(581, 566)
        self.formLayoutWidget = QtWidgets.QWidget(Form)
        self.formLayoutWidget.setGeometry(QtCore.QRect(50, 100, 171, 22))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.lb_name = QtWidgets.QLabel(self.formLayoutWidget)
        self.lb_name.setObjectName("lb_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lb_name)
        self.ed_name = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.ed_name.setObjectName("ed_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.ed_name)
        self.formLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(50, 150, 171, 22))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.lb_sex = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.lb_sex.setObjectName("lb_sex")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lb_sex)
        self.cb_sex = QtWidgets.QComboBox(self.formLayoutWidget_2)
        self.cb_sex.setObjectName("cb_sex")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cb_sex)
        self.formLayoutWidget_3 = QtWidgets.QWidget(Form)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(50, 200, 171, 22))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_4 = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_4.setContentsMargins(0, 0, 0, 0)
        self.formLayout_4.setObjectName("formLayout_4")
        self.ed_age = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.ed_age.setObjectName("ed_age")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.ed_age)
        self.lb_age = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.lb_age.setObjectName("lb_age")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lb_age)
        self.formLayoutWidget_4 = QtWidgets.QWidget(Form)
        self.formLayoutWidget_4.setGeometry(QtCore.QRect(50, 250, 171, 22))
        self.formLayoutWidget_4.setObjectName("formLayoutWidget_4")
        self.formLayout_5 = QtWidgets.QFormLayout(self.formLayoutWidget_4)
        self.formLayout_5.setContentsMargins(0, 0, 0, 0)
        self.formLayout_5.setObjectName("formLayout_5")
        self.ed_parent = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        self.ed_parent.setObjectName("ed_parent")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.ed_parent)
        self.lb_parent = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.lb_parent.setObjectName("lb_parent")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lb_parent)
        self.formLayoutWidget_5 = QtWidgets.QWidget(Form)
        self.formLayoutWidget_5.setGeometry(QtCore.QRect(50, 300, 171, 22))
        self.formLayoutWidget_5.setObjectName("formLayoutWidget_5")
        self.formLayout_6 = QtWidgets.QFormLayout(self.formLayoutWidget_5)
        self.formLayout_6.setContentsMargins(0, 0, 0, 0)
        self.formLayout_6.setObjectName("formLayout_6")
        self.ed_name_4 = QtWidgets.QLineEdit(self.formLayoutWidget_5)
        self.ed_name_4.setObjectName("ed_name_4")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.ed_name_4)
        self.lb_phone = QtWidgets.QLabel(self.formLayoutWidget_5)
        self.lb_phone.setObjectName("lb_phone")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lb_phone)
        self.formLayoutWidget_6 = QtWidgets.QWidget(Form)
        self.formLayoutWidget_6.setGeometry(QtCore.QRect(50, 350, 171, 22))
        self.formLayoutWidget_6.setObjectName("formLayoutWidget_6")
        self.formLayout_7 = QtWidgets.QFormLayout(self.formLayoutWidget_6)
        self.formLayout_7.setContentsMargins(0, 0, 0, 0)
        self.formLayout_7.setObjectName("formLayout_7")
        self.lb_card = QtWidgets.QLabel(self.formLayoutWidget_6)
        self.lb_card.setObjectName("lb_card")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lb_card)
        self.cb_card = QtWidgets.QComboBox(self.formLayoutWidget_6)
        self.cb_card.setObjectName("cb_card")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cb_card)
        self.formLayoutWidget_7 = QtWidgets.QWidget(Form)
        self.formLayoutWidget_7.setGeometry(QtCore.QRect(50, 400, 171, 22))
        self.formLayoutWidget_7.setObjectName("formLayoutWidget_7")
        self.formLayout_8 = QtWidgets.QFormLayout(self.formLayoutWidget_7)
        self.formLayout_8.setContentsMargins(0, 0, 0, 0)
        self.formLayout_8.setObjectName("formLayout_8")
        self.lb_lesson = QtWidgets.QLabel(self.formLayoutWidget_7)
        self.lb_lesson.setObjectName("lb_lesson")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lb_lesson)
        self.cb_lesson = QtWidgets.QComboBox(self.formLayoutWidget_7)
        self.cb_lesson.setObjectName("cb_lesson")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cb_lesson)
        self.bt_opencam = QtWidgets.QPushButton(Form)
        self.bt_opencam.setGeometry(QtCore.QRect(290, 90, 91, 41))
        self.bt_opencam.setObjectName("bt_opencam")
        self.bt_cutpic = QtWidgets.QPushButton(Form)
        self.bt_cutpic.setGeometry(QtCore.QRect(440, 90, 81, 41))
        self.bt_cutpic.setObjectName("bt_cutpic")
        self.lb_cam = QtWidgets.QLabel(Form)
        self.lb_cam.setGeometry(QtCore.QRect(300, 170, 231, 221))
        self.lb_cam.setText("")
        self.lb_cam.setObjectName("lb_cam")
        self.bt_confrim = QtWidgets.QPushButton(Form)
        self.bt_confrim.setGeometry(QtCore.QRect(150, 480, 91, 41))
        self.bt_confrim.setObjectName("bt_confrim")
        self.bt_back = QtWidgets.QPushButton(Form)
        self.bt_back.setGeometry(QtCore.QRect(340, 480, 81, 41))
        self.bt_back.setObjectName("bt_back")
        self.lb_head = QtWidgets.QLabel(Form)
        self.lb_head.setGeometry(QtCore.QRect(240, 40, 101, 31))
        self.lb_head.setObjectName("lb_head")
        self.formLayoutWidget.raise_()
        self.formLayoutWidget_2.raise_()
        self.formLayoutWidget_3.raise_()
        self.formLayoutWidget_3.raise_()
        self.formLayoutWidget_4.raise_()
        self.formLayoutWidget_5.raise_()
        self.formLayoutWidget_6.raise_()
        self.formLayoutWidget_7.raise_()
        self.bt_opencam.raise_()
        self.bt_cutpic.raise_()
        self.lb_cam.raise_()
        self.bt_confrim.raise_()
        self.bt_back.raise_()
        self.lb_head.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lb_name.setText(_translate("Form", "  姓名    "))
        self.lb_sex.setText(_translate("Form", "  性别      "))
        self.lb_age.setText(_translate("Form", "  年龄    "))
        self.lb_parent.setText(_translate("Form", "  家长    "))
        self.lb_phone.setText(_translate("Form", "  电话    "))
        self.lb_card.setText(_translate("Form", "  卡类      "))
        self.lb_lesson.setText(_translate("Form", "  课时      "))
        self.bt_opencam.setText(_translate("Form", "打开摄像头"))
        self.bt_cutpic.setText(_translate("Form", "截图"))
        self.bt_confrim.setText(_translate("Form", "确认录入"))
        self.bt_back.setText(_translate("Form", "返回"))
        self.lb_head.setText(_translate("Form", "新 学 员 录 入"))

