# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NewMember.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from MyQSS import myLabel

class Ui_NewMember(object):
    def setupUi(self, NewMember):
        NewMember.setObjectName("NewMember")
        NewMember.resize(1291, 651)
        NewMember.setStyleSheet("background-color: rgb(232, 232, 232);")
        self.lb_head = QtWidgets.QLabel(NewMember)
        self.lb_head.setGeometry(QtCore.QRect(420, 20, 401, 41))
        self.lb_head.setStyleSheet("font: 75 28pt \"楷体\";")
        self.lb_head.setObjectName("lb_head")
        self.groupBox_imageInfo = QtWidgets.QGroupBox(NewMember)
        self.groupBox_imageInfo.setGeometry(QtCore.QRect(620, 80, 461, 491))
        self.groupBox_imageInfo.setStyleSheet("background-color: rgb(221, 221, 221);")
        self.groupBox_imageInfo.setObjectName("groupBox_imageInfo")
        self.lb_cam = QtWidgets.QLabel(self.groupBox_imageInfo)
        self.lb_cam.setGeometry(QtCore.QRect(150, 60, 260, 346))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(200, 197, 198))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 197, 198))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 197, 198))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 197, 198))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 197, 198))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 197, 198))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 197, 198))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 197, 198))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 197, 198))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.lb_cam.setPalette(palette)
        self.lb_cam.setStyleSheet("background-color: rgb(200, 197, 198);")
        self.lb_cam.setText("")
        self.lb_cam.setObjectName("lb_cam")
        self.bt_opencam = QtWidgets.QPushButton(self.groupBox_imageInfo)
        self.bt_opencam.setGeometry(QtCore.QRect(30, 60, 91, 41))
        self.bt_opencam.setObjectName("bt_opencam")
        self.bt_cutpic = QtWidgets.QPushButton(self.groupBox_imageInfo)
        self.bt_cutpic.setGeometry(QtCore.QRect(30, 120, 91, 41))
        self.bt_cutpic.setObjectName("bt_cutpic")
        self.bt_openfile = QtWidgets.QPushButton(self.groupBox_imageInfo)
        self.bt_openfile.setGeometry(QtCore.QRect(30, 180, 91, 41))
        self.bt_openfile.setObjectName("bt_openfile")
        self.groupBox_BasicInfo = QtWidgets.QGroupBox(NewMember)
        self.groupBox_BasicInfo.setGeometry(QtCore.QRect(210, 80, 361, 491))
        self.groupBox_BasicInfo.setAutoFillBackground(False)
        self.groupBox_BasicInfo.setStyleSheet("background-color: rgb(221, 221, 221);")
        self.groupBox_BasicInfo.setObjectName("groupBox_BasicInfo")
        self.lb_name = QtWidgets.QLabel(self.groupBox_BasicInfo)
        self.lb_name.setGeometry(QtCore.QRect(70, 60, 61, 21))
        self.lb_name.setStyleSheet("font: 10pt \"宋体\";")
        self.lb_name.setObjectName("lb_name")
        self.et_name = QtWidgets.QLineEdit(self.groupBox_BasicInfo)
        self.et_name.setGeometry(QtCore.QRect(140, 60, 121, 21))
        self.et_name.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.et_name.setObjectName("et_name")
        self.lb_sex = QtWidgets.QLabel(self.groupBox_BasicInfo)
        self.lb_sex.setGeometry(QtCore.QRect(70, 110, 61, 21))
        self.lb_sex.setStyleSheet("font: 10pt \"宋体\";")
        self.lb_sex.setObjectName("lb_sex")
        self.lb_age = QtWidgets.QLabel(self.groupBox_BasicInfo)
        self.lb_age.setGeometry(QtCore.QRect(60, 160, 81, 21))
        self.lb_age.setStyleSheet("font: 10pt \"宋体\";")
        self.lb_age.setObjectName("lb_age")
        self.rb_man = QtWidgets.QRadioButton(self.groupBox_BasicInfo)
        self.rb_man.setGeometry(QtCore.QRect(150, 110, 41, 21))
        self.rb_man.setObjectName("rb_man")
        self.rb_woman = QtWidgets.QRadioButton(self.groupBox_BasicInfo)
        self.rb_woman.setGeometry(QtCore.QRect(210, 110, 41, 21))
        self.rb_woman.setObjectName("rb_woman")
        self.et_age = QtWidgets.QLineEdit(self.groupBox_BasicInfo)
        self.et_age.setGeometry(QtCore.QRect(140, 160, 121, 21))
        self.et_age.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.et_age.setObjectName("et_age")
        self.lb_parent = QtWidgets.QLabel(self.groupBox_BasicInfo)
        self.lb_parent.setGeometry(QtCore.QRect(70, 210, 61, 21))
        self.lb_parent.setStyleSheet("font: 10pt \"宋体\";")
        self.lb_parent.setObjectName("lb_parent")
        self.et_parent = QtWidgets.QLineEdit(self.groupBox_BasicInfo)
        self.et_parent.setGeometry(QtCore.QRect(140, 210, 121, 21))
        self.et_parent.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.et_parent.setObjectName("et_parent")
        self.lb_phone = QtWidgets.QLabel(self.groupBox_BasicInfo)
        self.lb_phone.setGeometry(QtCore.QRect(70, 260, 61, 21))
        self.lb_phone.setStyleSheet("font: 10pt \"宋体\";")
        self.lb_phone.setObjectName("lb_phone")
        self.et_phone = QtWidgets.QLineEdit(self.groupBox_BasicInfo)
        self.et_phone.setGeometry(QtCore.QRect(140, 260, 121, 21))
        self.et_phone.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.et_phone.setObjectName("et_phone")
        self.lb_card = QtWidgets.QLabel(self.groupBox_BasicInfo)
        self.lb_card.setGeometry(QtCore.QRect(70, 310, 61, 21))
        self.lb_card.setStyleSheet("font: 10pt \"宋体\";")
        self.lb_card.setObjectName("lb_card")
        self.cb_card = QtWidgets.QComboBox(self.groupBox_BasicInfo)
        self.cb_card.setGeometry(QtCore.QRect(150, 310, 81, 22))
        self.cb_card.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.cb_card.setObjectName("cb_card")
        self.lb_cichu = QtWidgets.QLabel(self.groupBox_BasicInfo)
        self.lb_cichu.setGeometry(QtCore.QRect(50, 360, 81, 21))
        self.lb_cichu.setStyleSheet("font: 10pt \"宋体\";")
        self.lb_cichu.setObjectName("lb_cichu")
        self.et_cichu = QtWidgets.QLineEdit(self.groupBox_BasicInfo)
        self.et_cichu.setGeometry(QtCore.QRect(140, 360, 121, 21))
        self.et_cichu.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.et_cichu.setObjectName("et_cichu")
        self.lb_money = QtWidgets.QLabel(self.groupBox_BasicInfo)
        self.lb_money.setGeometry(QtCore.QRect(50, 410, 81, 21))
        self.lb_money.setStyleSheet("font: 10pt \"宋体\";")
        self.lb_money.setObjectName("lb_money")
        self.et_money = QtWidgets.QLineEdit(self.groupBox_BasicInfo)
        self.et_money.setGeometry(QtCore.QRect(140, 410, 121, 21))
        self.et_money.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.et_money.setObjectName("et_money")
        self.bt_confrim = QtWidgets.QPushButton(NewMember)
        self.bt_confrim.setGeometry(QtCore.QRect(480, 590, 91, 41))
        self.bt_confrim.setObjectName("bt_confrim")
        self.bt_back = QtWidgets.QPushButton(NewMember)
        self.bt_back.setGeometry(QtCore.QRect(620, 590, 81, 41))
        self.bt_back.setObjectName("bt_back")
        self.lb_toOld = myLabel(NewMember)
        self.lb_toOld.setGeometry(QtCore.QRect(910, 600, 101, 21))
        self.lb_toOld.setObjectName("lb_toOld")

        self.retranslateUi(NewMember)
        QtCore.QMetaObject.connectSlotsByName(NewMember)

    def retranslateUi(self, NewMember):
        _translate = QtCore.QCoreApplication.translate
        NewMember.setWindowTitle(_translate("NewMember", "Form"))
        self.lb_head.setText(_translate("NewMember", "新 学 员 录 入 系 统"))
        self.groupBox_imageInfo.setTitle(_translate("NewMember", "图像信息"))
        self.bt_opencam.setText(_translate("NewMember", "打开摄像头"))
        self.bt_cutpic.setText(_translate("NewMember", "截图"))
        self.bt_openfile.setText(_translate("NewMember", "打开文件"))
        self.groupBox_BasicInfo.setTitle(_translate("NewMember", "基本信息"))
        self.lb_name.setText(_translate("NewMember", "学员姓名"))
        self.lb_sex.setText(_translate("NewMember", "学员性别"))
        self.lb_age.setText(_translate("NewMember", "学员年龄(岁)"))
        self.rb_man.setText(_translate("NewMember", "男"))
        self.rb_woman.setText(_translate("NewMember", "女"))
        self.lb_parent.setText(_translate("NewMember", "学员家长"))
        self.lb_phone.setText(_translate("NewMember", "联系方式"))
        self.lb_card.setText(_translate("NewMember", "办卡模式"))
        self.lb_cichu.setText(_translate("NewMember", "课时次数(次)"))
        self.lb_money.setText(_translate("NewMember", "办卡金额(元)"))
        self.bt_confrim.setText(_translate("NewMember", "确认录入"))
        self.bt_back.setText(_translate("NewMember", "清空"))
        self.lb_toOld.setText(_translate("NewMember", "已经是老学员"))

