# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NewMember.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_NewMember(object):
    def setupUi(self, NewMember):
        NewMember.setObjectName("NewMember")
        NewMember.resize(1291, 651)
        NewMember.setStyleSheet("background-color: rgb(232, 232, 232);")
        self.left_widget = QtWidgets.QWidget(NewMember)
        self.left_widget.setGeometry(QtCore.QRect(0, 0, 171, 661))
        self.left_widget.setStyleSheet("background:#DDDDDD")
        self.left_widget.setObjectName("left_widget")
        self.listFunc = QtWidgets.QListWidget(self.left_widget)
        self.listFunc.setGeometry(QtCore.QRect(20, 60, 131, 441))
        self.listFunc.setStyleSheet("QListWidget#listFunc{\n"
"    outline: 0px;\n"
"    border:0px;\n"
"    min-width: 120px;\n"
"    color: Black;\n"
"    background: #DDDDDD;\n"
"}\n"
"\n"
"QListWidget#listFunc::Item{\n"
"     height:30px;\n"
"}\n"
"QListWidget#listFunc::Item:selected {\n"
"    background: rgb(49, 194, 124);\n"
"    border-radius:1.5px;\n"
"   \n"
"}\n"
"")
        self.listFunc.setObjectName("listFunc")
        item = QtWidgets.QListWidgetItem()
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../GUI/resource/add_c.svg"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        item.setIcon(icon)
        self.listFunc.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../GUI/resource/up_c.svg"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        item.setIcon(icon1)
        self.listFunc.addItem(item)
        self.label = QtWidgets.QLabel(self.left_widget)
        self.label.setGeometry(QtCore.QRect(40, 20, 81, 21))
        self.label.setStyleSheet("font: 75 14pt \"黑体\";")
        self.label.setObjectName("label")
        self.stackedWidget = QtWidgets.QStackedWidget(NewMember)
        self.stackedWidget.setGeometry(QtCore.QRect(220, 20, 1041, 611))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.groupBox_imageInfo = QtWidgets.QGroupBox(self.page)
        self.groupBox_imageInfo.setGeometry(QtCore.QRect(500, 50, 351, 491))
        self.groupBox_imageInfo.setStyleSheet("")
        self.groupBox_imageInfo.setObjectName("groupBox_imageInfo")
        self.lb_cam_new = QtWidgets.QLabel(self.groupBox_imageInfo)
        self.lb_cam_new.setGeometry(QtCore.QRect(30, 20, 260, 346))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(200, 197, 198))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 197, 198))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 197, 198))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 197, 198))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 197, 198))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 197, 198))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 197, 198))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 197, 198))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 197, 198))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.lb_cam_new.setPalette(palette)
        self.lb_cam_new.setStyleSheet("background-color: rgb(200, 197, 198);")
        self.lb_cam_new.setText("")
        self.lb_cam_new.setObjectName("lb_cam_new")
        self.bt_opencam_new = QtWidgets.QPushButton(self.groupBox_imageInfo)
        self.bt_opencam_new.setGeometry(QtCore.QRect(40, 380, 101, 41))
        self.bt_opencam_new.setObjectName("bt_opencam_new")
        self.bt_cutpic_new = QtWidgets.QPushButton(self.groupBox_imageInfo)
        self.bt_cutpic_new.setGeometry(QtCore.QRect(180, 380, 111, 41))
        self.bt_cutpic_new.setObjectName("bt_cutpic_new")
        self.bt_openfile_new = QtWidgets.QPushButton(self.groupBox_imageInfo)
        self.bt_openfile_new.setGeometry(QtCore.QRect(40, 440, 101, 41))
        self.bt_openfile_new.setObjectName("bt_openfile_new")
        self.bt_clearpic_new = QtWidgets.QPushButton(self.groupBox_imageInfo)
        self.bt_clearpic_new.setGeometry(QtCore.QRect(180, 440, 111, 41))
        self.bt_clearpic_new.setObjectName("bt_clearpic_new")
        self.groupBox_BasicInfo = QtWidgets.QGroupBox(self.page)
        self.groupBox_BasicInfo.setGeometry(QtCore.QRect(100, 50, 361, 491))
        self.groupBox_BasicInfo.setAutoFillBackground(False)
        self.groupBox_BasicInfo.setStyleSheet("")
        self.groupBox_BasicInfo.setObjectName("groupBox_BasicInfo")
        self.lb_name_new = QtWidgets.QLabel(self.groupBox_BasicInfo)
        self.lb_name_new.setGeometry(QtCore.QRect(70, 60, 71, 21))
        self.lb_name_new.setStyleSheet("font: 10pt \"宋体\";")
        self.lb_name_new.setObjectName("lb_name_new")
        self.et_name_new = QtWidgets.QLineEdit(self.groupBox_BasicInfo)
        self.et_name_new.setGeometry(QtCore.QRect(180, 60, 121, 21))
        self.et_name_new.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.et_name_new.setObjectName("et_name_new")
        self.lb_sex_new = QtWidgets.QLabel(self.groupBox_BasicInfo)
        self.lb_sex_new.setGeometry(QtCore.QRect(70, 110, 91, 21))
        self.lb_sex_new.setStyleSheet("font: 10pt \"宋体\";")
        self.lb_sex_new.setObjectName("lb_sex_new")
        self.lb_age_new = QtWidgets.QLabel(self.groupBox_BasicInfo)
        self.lb_age_new.setGeometry(QtCore.QRect(60, 160, 101, 21))
        self.lb_age_new.setStyleSheet("font: 10pt \"宋体\";")
        self.lb_age_new.setObjectName("lb_age_new")
        self.rb_man_new = QtWidgets.QRadioButton(self.groupBox_BasicInfo)
        self.rb_man_new.setGeometry(QtCore.QRect(190, 110, 41, 21))
        self.rb_man_new.setObjectName("rb_man_new")
        self.rb_woman_new = QtWidgets.QRadioButton(self.groupBox_BasicInfo)
        self.rb_woman_new.setGeometry(QtCore.QRect(260, 110, 41, 21))
        self.rb_woman_new.setObjectName("rb_woman_new")
        self.et_age_new = QtWidgets.QLineEdit(self.groupBox_BasicInfo)
        self.et_age_new.setGeometry(QtCore.QRect(180, 160, 121, 21))
        self.et_age_new.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.et_age_new.setObjectName("et_age_new")
        self.lb_parent_new = QtWidgets.QLabel(self.groupBox_BasicInfo)
        self.lb_parent_new.setGeometry(QtCore.QRect(70, 210, 71, 21))
        self.lb_parent_new.setStyleSheet("font: 10pt \"宋体\";")
        self.lb_parent_new.setObjectName("lb_parent_new")
        self.et_parent_new = QtWidgets.QLineEdit(self.groupBox_BasicInfo)
        self.et_parent_new.setGeometry(QtCore.QRect(180, 200, 121, 21))
        self.et_parent_new.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.et_parent_new.setObjectName("et_parent_new")
        self.lb_phone_new = QtWidgets.QLabel(self.groupBox_BasicInfo)
        self.lb_phone_new.setGeometry(QtCore.QRect(70, 260, 81, 21))
        self.lb_phone_new.setStyleSheet("font: 10pt \"宋体\";")
        self.lb_phone_new.setObjectName("lb_phone_new")
        self.et_phone_new = QtWidgets.QLineEdit(self.groupBox_BasicInfo)
        self.et_phone_new.setGeometry(QtCore.QRect(180, 250, 121, 21))
        self.et_phone_new.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.et_phone_new.setObjectName("et_phone_new")
        self.lb_card_new = QtWidgets.QLabel(self.groupBox_BasicInfo)
        self.lb_card_new.setGeometry(QtCore.QRect(70, 300, 101, 21))
        self.lb_card_new.setStyleSheet("font: 10pt \"宋体\";")
        self.lb_card_new.setObjectName("lb_card_new")
        self.cb_card_new = QtWidgets.QComboBox(self.groupBox_BasicInfo)
        self.cb_card_new.setGeometry(QtCore.QRect(200, 300, 81, 22))
        self.cb_card_new.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.cb_card_new.setObjectName("cb_card_new")
        self.lb_cichu_new = QtWidgets.QLabel(self.groupBox_BasicInfo)
        self.lb_cichu_new.setGeometry(QtCore.QRect(50, 390, 101, 21))
        self.lb_cichu_new.setStyleSheet("font: 10pt \"宋体\";")
        self.lb_cichu_new.setObjectName("lb_cichu_new")
        self.et_cichu_new = QtWidgets.QLineEdit(self.groupBox_BasicInfo)
        self.et_cichu_new.setGeometry(QtCore.QRect(180, 390, 121, 21))
        self.et_cichu_new.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.et_cichu_new.setObjectName("et_cichu_new")
        self.lb_money_new = QtWidgets.QLabel(self.groupBox_BasicInfo)
        self.lb_money_new.setGeometry(QtCore.QRect(50, 440, 111, 21))
        self.lb_money_new.setStyleSheet("font: 10pt \"宋体\";")
        self.lb_money_new.setObjectName("lb_money_new")
        self.et_money_new = QtWidgets.QLineEdit(self.groupBox_BasicInfo)
        self.et_money_new.setGeometry(QtCore.QRect(180, 440, 121, 21))
        self.et_money_new.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.et_money_new.setObjectName("et_money_new")
        self.lb_classitem_new = QtWidgets.QLabel(self.groupBox_BasicInfo)
        self.lb_classitem_new.setGeometry(QtCore.QRect(70, 350, 81, 21))
        self.lb_classitem_new.setStyleSheet("font: 10pt \"宋体\";")
        self.lb_classitem_new.setObjectName("lb_classitem_new")
        self.cb_classitem_new = QtWidgets.QComboBox(self.groupBox_BasicInfo)
        self.cb_classitem_new.setGeometry(QtCore.QRect(200, 350, 81, 22))
        self.cb_classitem_new.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.cb_classitem_new.setObjectName("cb_classitem_new")
        self.lb_head_newmember = QtWidgets.QLabel(self.page)
        self.lb_head_newmember.setGeometry(QtCore.QRect(290, 0, 401, 41))
        self.lb_head_newmember.setStyleSheet("font: 75 28pt \"楷体\";")
        self.lb_head_newmember.setObjectName("lb_head_newmember")
        self.gb_option_2 = QtWidgets.QGroupBox(self.page)
        self.gb_option_2.setGeometry(QtCore.QRect(100, 540, 751, 61))
        self.gb_option_2.setObjectName("gb_option_2")
        self.bt_confrim_new = QtWidgets.QPushButton(self.gb_option_2)
        self.bt_confrim_new.setGeometry(QtCore.QRect(230, 10, 131, 41))
        self.bt_confrim_new.setObjectName("bt_confrim_new")
        self.bt_back_new = QtWidgets.QPushButton(self.gb_option_2)
        self.bt_back_new.setGeometry(QtCore.QRect(400, 10, 121, 41))
        self.bt_back_new.setObjectName("bt_back_new")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.lb_head_old = QtWidgets.QLabel(self.page_2)
        self.lb_head_old.setGeometry(QtCore.QRect(310, 10, 401, 41))
        self.lb_head_old.setStyleSheet("font: 75 28pt \"楷体\";")
        self.lb_head_old.setObjectName("lb_head_old")
        self.groupBox_BasicInfo_2 = QtWidgets.QGroupBox(self.page_2)
        self.groupBox_BasicInfo_2.setGeometry(QtCore.QRect(0, 60, 1031, 541))
        self.groupBox_BasicInfo_2.setAutoFillBackground(False)
        self.groupBox_BasicInfo_2.setStyleSheet("")
        self.groupBox_BasicInfo_2.setTitle("")
        self.groupBox_BasicInfo_2.setObjectName("groupBox_BasicInfo_2")
        self.gb_info = QtWidgets.QGroupBox(self.groupBox_BasicInfo_2)
        self.gb_info.setGeometry(QtCore.QRect(340, 30, 261, 471))
        self.gb_info.setObjectName("gb_info")
        self.lb_name_old = QtWidgets.QLabel(self.gb_info)
        self.lb_name_old.setGeometry(QtCore.QRect(20, 40, 61, 21))
        self.lb_name_old.setStyleSheet("font: 10pt \"宋体\";")
        self.lb_name_old.setObjectName("lb_name_old")
        self.et_name_old = QtWidgets.QLineEdit(self.gb_info)
        self.et_name_old.setGeometry(QtCore.QRect(110, 40, 121, 21))
        self.et_name_old.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.et_name_old.setObjectName("et_name_old")
        self.lb_phone_old = QtWidgets.QLabel(self.gb_info)
        self.lb_phone_old.setGeometry(QtCore.QRect(20, 90, 61, 21))
        self.lb_phone_old.setStyleSheet("font: 10pt \"宋体\";")
        self.lb_phone_old.setObjectName("lb_phone_old")
        self.et_sex_old = QtWidgets.QLineEdit(self.gb_info)
        self.et_sex_old.setGeometry(QtCore.QRect(110, 90, 121, 21))
        self.et_sex_old.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.et_sex_old.setObjectName("et_phone_old_2")
        self.lb_age_old = QtWidgets.QLabel(self.gb_info)
        self.lb_age_old.setGeometry(QtCore.QRect(10, 170, 81, 21))
        self.lb_age_old.setStyleSheet("font: 10pt \"宋体\";")
        self.lb_age_old.setObjectName("lb_age_old")
        self.et_age_old = QtWidgets.QLineEdit(self.gb_info)
        self.et_age_old.setGeometry(QtCore.QRect(110, 170, 121, 21))
        self.et_age_old.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.et_age_old.setObjectName("et_age_old")
        self.lb_parent_old = QtWidgets.QLabel(self.gb_info)
        self.lb_parent_old.setGeometry(QtCore.QRect(20, 220, 71, 21))
        self.lb_parent_old.setStyleSheet("font: 10pt \"宋体\";")
        self.lb_parent_old.setObjectName("lb_parent_old")
        self.et_parent_old = QtWidgets.QLineEdit(self.gb_info)
        self.et_parent_old.setGeometry(QtCore.QRect(110, 220, 121, 21))
        self.et_parent_old.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.et_parent_old.setObjectName("et_parent_old")
        self.lb_card_old = QtWidgets.QLabel(self.gb_info)
        self.lb_card_old.setGeometry(QtCore.QRect(20, 260, 81, 21))
        self.lb_card_old.setStyleSheet("font: 10pt \"宋体\";")
        self.lb_card_old.setObjectName("lb_card_old")
        self.cb_card_old = QtWidgets.QComboBox(self.gb_info)
        self.cb_card_old.setGeometry(QtCore.QRect(130, 260, 81, 22))
        self.cb_card_old.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.cb_card_old.setObjectName("cb_card_old")
        self.lb_classitem_old = QtWidgets.QLabel(self.gb_info)
        self.lb_classitem_old.setGeometry(QtCore.QRect(20, 310, 81, 21))
        self.lb_classitem_old.setStyleSheet("font: 10pt \"宋体\";")
        self.lb_classitem_old.setObjectName("lb_classitem_old")
        self.cb_classitem_old = QtWidgets.QComboBox(self.gb_info)
        self.cb_classitem_old.setGeometry(QtCore.QRect(130, 310, 81, 22))
        self.cb_classitem_old.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.cb_classitem_old.setObjectName("cb_classitem_old")
        self.lb_cichu_old = QtWidgets.QLabel(self.gb_info)
        self.lb_cichu_old.setGeometry(QtCore.QRect(10, 360, 91, 21))
        self.lb_cichu_old.setStyleSheet("font: 10pt \"宋体\";")
        self.lb_cichu_old.setObjectName("lb_cichu_old")
        self.et_cichu__old = QtWidgets.QLineEdit(self.gb_info)
        self.et_cichu__old.setGeometry(QtCore.QRect(110, 360, 121, 21))
        self.et_cichu__old.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.et_cichu__old.setObjectName("et_cichu__old")
        self.lb_money__old = QtWidgets.QLabel(self.gb_info)
        self.lb_money__old.setGeometry(QtCore.QRect(10, 410, 91, 21))
        self.lb_money__old.setStyleSheet("font: 10pt \"宋体\";")
        self.lb_money__old.setObjectName("lb_money__old")
        self.et_money_old = QtWidgets.QLineEdit(self.gb_info)
        self.et_money_old.setGeometry(QtCore.QRect(110, 410, 121, 21))
        self.et_money_old.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.et_money_old.setObjectName("et_money_old")
        self.lb_sex_old = QtWidgets.QLabel(self.gb_info)
        self.lb_sex_old.setGeometry(QtCore.QRect(20, 130, 61, 21))
        self.lb_sex_old.setStyleSheet("font: 10pt \"宋体\";")
        self.lb_sex_old.setObjectName("lb_phone_old_2")
        self.et_phone_old = QtWidgets.QLineEdit(self.gb_info)
        self.et_phone_old.setGeometry(QtCore.QRect(110, 130, 121, 21))
        self.et_phone_old.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.et_phone_old.setObjectName("et_phone_old")
        self.gb_option = QtWidgets.QGroupBox(self.groupBox_BasicInfo_2)
        self.gb_option.setGeometry(QtCore.QRect(20, 30, 301, 481))
        self.gb_option.setObjectName("gb_option")
        self.btn_confirm_old = QtWidgets.QPushButton(self.gb_option)
        self.btn_confirm_old.setGeometry(QtCore.QRect(20, 300, 261, 61))
        self.btn_confirm_old.setObjectName("btn_confirm_old")
        self.btn_clear__old = QtWidgets.QPushButton(self.gb_option)
        self.btn_clear__old.setGeometry(QtCore.QRect(20, 390, 261, 61))
        self.btn_clear__old.setObjectName("btn_clear__old")
        self.label_22 = QtWidgets.QLabel(self.gb_option)
        self.label_22.setGeometry(QtCore.QRect(21, 71, 75, 16))
        self.label_22.setObjectName("label_22")
        self.lb_result = QtWidgets.QLabel(self.gb_option)
        self.lb_result.setGeometry(QtCore.QRect(103, 71, 221, 16))
        self.lb_result.setText("")
        self.lb_result.setObjectName("lb_result")
        self.tv_search_student = QtWidgets.QTableView(self.gb_option)
        self.tv_search_student.setGeometry(QtCore.QRect(20, 90, 261, 192))
        self.tv_search_student.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tv_search_student.setObjectName("tv_search_coach")
        self.layoutWidget = QtWidgets.QWidget(self.gb_option)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 30, 261, 30))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.btn_search = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_search.setObjectName("btn_search")
        self.gridLayout_3.addWidget(self.btn_search, 0, 2, 1, 1)
        self.le_search_term = QtWidgets.QLineEdit(self.layoutWidget)
        self.le_search_term.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.le_search_term.setObjectName("le_search_term")
        self.gridLayout_3.addWidget(self.le_search_term, 0, 1, 1, 1)
        self.lb_check_phone = QtWidgets.QLabel(self.layoutWidget)
        self.lb_check_phone.setObjectName("lb_check_phone")
        self.gridLayout_3.addWidget(self.lb_check_phone, 0, 0, 1, 1)
        self.gb_pic = QtWidgets.QGroupBox(self.groupBox_BasicInfo_2)
        self.gb_pic.setGeometry(QtCore.QRect(610, 30, 331, 491))
        self.gb_pic.setObjectName("gb_pic")
        self.lb_cam_old = QtWidgets.QLabel(self.gb_pic)
        self.lb_cam_old.setGeometry(QtCore.QRect(30, 20, 260, 361))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(200, 197, 198))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 197, 198))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 197, 198))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 197, 198))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 197, 198))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 197, 198))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 197, 198))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 197, 198))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 197, 198))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.lb_cam_old.setPalette(palette)
        self.lb_cam_old.setStyleSheet("background-color: rgb(200, 197, 198);")
        self.lb_cam_old.setText("")
        self.lb_cam_old.setObjectName("lb_cam_old")
        self.pb_opencam_old = QtWidgets.QPushButton(self.gb_pic)
        self.pb_opencam_old.setGeometry(QtCore.QRect(50, 390, 101, 41))
        self.pb_opencam_old.setObjectName("pb_opencam_old")
        self.pb_clearpic_old = QtWidgets.QPushButton(self.gb_pic)
        self.pb_clearpic_old.setGeometry(QtCore.QRect(170, 440, 101, 41))
        self.pb_clearpic_old.setObjectName("pb_clearpic_old")
        self.pb_openfile_old = QtWidgets.QPushButton(self.gb_pic)
        self.pb_openfile_old.setGeometry(QtCore.QRect(50, 440, 101, 41))
        self.pb_openfile_old.setObjectName("pb_openfile_old")
        self.pb_cutlpic_old = QtWidgets.QPushButton(self.gb_pic)
        self.pb_cutlpic_old.setGeometry(QtCore.QRect(170, 390, 101, 41))
        self.pb_cutlpic_old.setObjectName("pb_cutlpic_old")
        self.stackedWidget.addWidget(self.page_2)

        self.retranslateUi(NewMember)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(NewMember)

    def retranslateUi(self, NewMember):
        _translate = QtCore.QCoreApplication.translate
        NewMember.setWindowTitle(_translate("NewMember", "Form"))
        __sortingEnabled = self.listFunc.isSortingEnabled()
        self.listFunc.setSortingEnabled(False)
        item = self.listFunc.item(0)
        item.setText(_translate("NewMember", "添加新学员"))
        item = self.listFunc.item(1)
        item.setText(_translate("NewMember", "老学员续卡"))
        self.listFunc.setSortingEnabled(__sortingEnabled)
        self.label.setText(_translate("NewMember", "菜 单 栏"))
        self.groupBox_imageInfo.setTitle(_translate("NewMember", "图像信息"))
        self.bt_opencam_new.setText(_translate("NewMember", "打开摄像头"))
        self.bt_cutpic_new.setText(_translate("NewMember", "截图"))
        self.bt_openfile_new.setText(_translate("NewMember", "打开文件"))
        self.bt_clearpic_new.setText(_translate("NewMember", "清空图像"))
        self.groupBox_BasicInfo.setTitle(_translate("NewMember", "基本信息"))
        self.lb_name_new.setText(_translate("NewMember", "学员姓名"))
        self.lb_sex_new.setText(_translate("NewMember", "学员性别"))
        self.lb_age_new.setText(_translate("NewMember", "学员年龄(岁)"))
        self.rb_man_new.setText(_translate("NewMember", "男"))
        self.rb_woman_new.setText(_translate("NewMember", "女"))
        self.lb_parent_new.setText(_translate("NewMember", "学员家长"))
        self.lb_phone_new.setText(_translate("NewMember", "联系方式"))
        self.lb_card_new.setText(_translate("NewMember", "办卡模式"))
        self.lb_cichu_new.setText(_translate("NewMember", "课时次数(次)"))
        self.lb_money_new.setText(_translate("NewMember", "办卡金额(元)"))
        self.lb_classitem_new.setText(_translate("NewMember", "课程种类"))
        self.lb_head_newmember.setText(_translate("NewMember", "新 学 员 录 入 系 统"))
        self.gb_option_2.setTitle(_translate("NewMember", "控制栏"))
        self.bt_confrim_new.setText(_translate("NewMember", "确认录入"))
        self.bt_back_new.setText(_translate("NewMember", "返回"))
        self.lb_head_old.setText(_translate("NewMember", "老 学 员 续 卡 系 统"))
        self.gb_info.setTitle(_translate("NewMember", "基本信息"))
        self.lb_name_old.setText(_translate("NewMember", "学员姓名"))
        self.lb_phone_old.setText(_translate("NewMember", "联系方式"))
        self.lb_age_old.setText(_translate("NewMember", "学员年龄(岁)"))
        self.lb_parent_old.setText(_translate("NewMember", "学员家长"))
        self.lb_card_old.setText(_translate("NewMember", "办卡模式"))
        self.lb_classitem_old.setText(_translate("NewMember", "课程种类"))
        self.lb_cichu_old.setText(_translate("NewMember", "添加次数(次)"))
        self.lb_money__old.setText(_translate("NewMember", "办卡金额(元)"))
        self.lb_sex_old.setText(_translate("NewMember", "学员性别"))
        self.gb_option.setTitle(_translate("NewMember", "操作栏"))
        self.btn_confirm_old.setText(_translate("NewMember", "确认信息"))
        self.btn_clear__old.setText(_translate("NewMember", "清空信息"))
        self.label_22.setText(_translate("NewMember", "搜索状态："))
        self.btn_search.setText(_translate("NewMember", "查询"))
        self.lb_check_phone.setText(_translate("NewMember", "电话号码"))
        self.gb_pic.setTitle(_translate("NewMember", "图像信息"))
        self.pb_opencam_old.setText(_translate("NewMember", "打开摄像头"))
        self.pb_clearpic_old.setText(_translate("NewMember", "清空图像"))
        self.pb_openfile_old.setText(_translate("NewMember", "打开文件"))
        self.pb_cutlpic_old.setText(_translate("NewMember", "截图"))

