# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\waibao\newUser.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_newUser(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(700, 500)
        Dialog.setMinimumSize(QtCore.QSize(700, 500))
        Dialog.setMaximumSize(QtCore.QSize(700, 500))
        Dialog.setMouseTracking(False)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(80, 50, 591, 221))
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 20, 551, 181))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 0, 0, 1, 1)
        self.edit_name = QtWidgets.QLineEdit(self.layoutWidget)
        self.edit_name.setObjectName("edit_name")
        self.gridLayout_4.addWidget(self.edit_name, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 0, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 0, 3, 1, 1)
        self.edit_phone = QtWidgets.QLineEdit(self.layoutWidget)
        self.edit_phone.setObjectName("edit_phone")
        self.gridLayout_4.addWidget(self.edit_phone, 0, 4, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 0, 5, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 1, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 2, 0, 1, 1)
        self.edit_parent = QtWidgets.QLineEdit(self.layoutWidget)
        self.edit_parent.setObjectName("edit_parent")
        self.gridLayout_4.addWidget(self.edit_parent, 2, 1, 1, 1)
        self.cb_gender = QtWidgets.QComboBox(self.layoutWidget)
        self.cb_gender.setObjectName("cb_gender")
        self.cb_gender.addItem("")
        self.cb_gender.addItem("")
        self.gridLayout_4.addWidget(self.cb_gender, 1, 1, 1, 1)
        self.cb_type = QtWidgets.QComboBox(self.layoutWidget)
        self.cb_type.setObjectName("cb_type")
        self.cb_type.addItem("")
        self.cb_type.addItem("")
        self.cb_type.addItem("")
        self.gridLayout_4.addWidget(self.cb_type, 1, 4, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(80, 310, 491, 81))
        self.groupBox_2.setObjectName("groupBox_2")
        self.splitter = QtWidgets.QSplitter(self.groupBox_2)
        self.splitter.setGeometry(QtCore.QRect(30, 20, 279, 28))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.btn_clear = QtWidgets.QPushButton(self.splitter)
        self.btn_clear.setObjectName("btn_clear")
        self.btn_insert = QtWidgets.QPushButton(self.splitter)
        self.btn_insert.setObjectName("btn_insert")
        self.btn_newadd = QtWidgets.QPushButton(self.splitter)
        self.btn_newadd.setObjectName("btn_newadd")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "添加员工信息"))
        self.groupBox.setTitle(_translate("Dialog", "员工信息(带*的为必填)"))
        self.label.setText(_translate("Dialog", "学员姓名："))
        self.label_6.setText(_translate("Dialog", "*"))
        self.label_4.setText(_translate("Dialog", "联系方式："))
        self.label_7.setText(_translate("Dialog", "*"))
        self.label_2.setText(_translate("Dialog", "学员性别："))
        self.label_5.setText(_translate("Dialog", "办卡模式:"))
        self.label_3.setText(_translate("Dialog", "学员家长："))
        self.cb_gender.setItemText(0, _translate("Dialog", "男"))
        self.cb_gender.setItemText(1, _translate("Dialog", "女"))
        self.cb_type.setItemText(0, _translate("Dialog", "1"))
        self.cb_type.setItemText(1, _translate("Dialog", "2"))
        self.cb_type.setItemText(2, _translate("Dialog", "3"))
        self.groupBox_2.setTitle(_translate("Dialog", "菜单"))
        self.btn_clear.setText(_translate("Dialog", "清空"))
        self.btn_insert.setText(_translate("Dialog", "录入"))
        self.btn_newadd.setText(_translate("Dialog", "新添加"))
