# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\waibao\schUpdateWin.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SchUpdate(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(700, 500)
        Dialog.setMinimumSize(QtCore.QSize(700, 500))
        Dialog.setMaximumSize(QtCore.QSize(700, 500))
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(60, 80, 591, 311))
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 30, 551, 261))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.edit_name = QtWidgets.QLineEdit(self.layoutWidget)
        self.edit_name.setObjectName("edit_name")
        self.gridLayout_4.addWidget(self.edit_name, 0, 1, 1, 1)
        self.edit_phone = QtWidgets.QLineEdit(self.layoutWidget)
        self.edit_phone.setObjectName("edit_phone")
        self.gridLayout_4.addWidget(self.edit_phone, 0, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 1, 2, 1, 1)
        self.edit_parent = QtWidgets.QLineEdit(self.layoutWidget)
        self.edit_parent.setObjectName("edit_parent")
        self.gridLayout_4.addWidget(self.edit_parent, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 0, 0, 1, 1)
        self.edit_gender = QtWidgets.QLineEdit(self.layoutWidget)
        self.edit_gender.setObjectName("edit_gender")
        self.gridLayout_4.addWidget(self.edit_gender, 1, 1, 1, 1)
        self.edit_type = QtWidgets.QLineEdit(self.layoutWidget)
        self.edit_type.setObjectName("edit_type")
        self.gridLayout_4.addWidget(self.edit_type, 1, 3, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(60, 400, 591, 80))
        self.groupBox_2.setObjectName("groupBox_2")
        self.btn_update = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_update.setGeometry(QtCore.QRect(20, 30, 93, 28))
        self.btn_update.setObjectName("btn_update")
        self.btn_next = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_next.setGeometry(QtCore.QRect(140, 30, 93, 28))
        self.btn_next.setObjectName("btn_next")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(60, 40, 591, 30))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.edit_search_term = QtWidgets.QLineEdit(self.widget)
        self.edit_search_term.setObjectName("edit_search_term")
        self.horizontalLayout.addWidget(self.edit_search_term)
        self.btn_search = QtWidgets.QPushButton(self.widget)
        self.btn_search.setText("")
        self.btn_search.setObjectName("btn_search")
        self.horizontalLayout.addWidget(self.btn_search)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox.setTitle(_translate("Dialog", "查询信息"))
        self.label_5.setText(_translate("Dialog", "办卡模式:"))
        self.label_3.setText(_translate("Dialog", "学员性别："))
        self.label_8.setText(_translate("Dialog", "学员家长："))
        self.label_4.setText(_translate("Dialog", "联系方式："))
        self.label_2.setText(_translate("Dialog", "学员姓名："))
        self.groupBox_2.setTitle(_translate("Dialog", "操作栏"))
        self.btn_update.setText(_translate("Dialog", "更新"))
        self.btn_next.setText(_translate("Dialog", "下一位"))
        self.label.setText(_translate("Dialog", "搜索关键词："))
