# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\waibao\updateClass.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from myUI import ComboCheckBox

class Ui_updateClass(object):
    def setupUi(self, updateClass):
        updateClass.setObjectName("updateClass")
        updateClass.resize(641, 448)
        updateClass.setMinimumSize(QtCore.QSize(641, 448))
        updateClass.setMaximumSize(QtCore.QSize(641, 448))
        self.groupBox = QtWidgets.QGroupBox(updateClass)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 621, 51))
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 601, 23))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.cb_year = QtWidgets.QComboBox(self.layoutWidget)
        self.cb_year.setObjectName("cb_year")
        self.cb_year.addItem("")
        self.cb_year.addItem("")
        self.cb_year.addItem("")
        self.cb_year.addItem("")
        self.cb_year.addItem("")
        self.cb_year.addItem("")
        self.cb_year.addItem("")
        self.cb_year.addItem("")
        self.cb_year.addItem("")
        self.cb_year.addItem("")
        self.cb_year.addItem("")
        self.cb_year.addItem("")
        self.gridLayout.addWidget(self.cb_year, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 1)
        self.cb_week = QtWidgets.QComboBox(self.layoutWidget)
        self.cb_week.setObjectName("cb_week")
        self.cb_week.addItem("")
        self.cb_week.addItem("")
        self.cb_week.addItem("")
        self.cb_week.addItem("")
        self.cb_week.addItem("")
        self.cb_week.addItem("")
        self.cb_week.addItem("")
        self.cb_week.addItem("")
        self.cb_week.addItem("")
        self.cb_week.addItem("")
        self.cb_week.addItem("")
        self.gridLayout.addWidget(self.cb_week, 0, 3, 1, 1)
        self.gridLayout.setColumnStretch(1, 1)
        self.gridLayout.setColumnStretch(3, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(updateClass)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 80, 301, 361))
        self.groupBox_2.setObjectName("groupBox_2")
        self.tv_show_mem = QtWidgets.QTableView(self.groupBox_2)
        self.tv_show_mem.setGeometry(QtCore.QRect(10, 20, 271, 321))
        self.tv_show_mem.setObjectName("tv_show_mem")
        self.groupBox_3 = QtWidgets.QGroupBox(updateClass)
        self.groupBox_3.setGeometry(QtCore.QRect(330, 160, 301, 101))
        self.groupBox_3.setObjectName("groupBox_3")
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 20, 281, 71))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
        self.cb_coach = QtWidgets.QComboBox(self.layoutWidget1)
        self.cb_coach.setObjectName("cb_coach")
        self.cb_coach.addItem("")
        self.gridLayout_2.addWidget(self.cb_coach, 0, 1, 1, 1)
        items = ['周一','周二','周三','周四','周五','周六','周日']
        self.cb_day = ComboCheckBox(items, self.layoutWidget1)
        self.cb_day.setObjectName("cb_day")
        self.gridLayout_2.addWidget(self.cb_day, 1, 1, 1, 1)
        self.gridLayout_2.setColumnStretch(1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(updateClass)
        self.groupBox_4.setGeometry(QtCore.QRect(330, 270, 301, 171))
        self.groupBox_4.setObjectName("groupBox_4")
        self.btn_flush = QtWidgets.QPushButton(self.groupBox_4)
        self.btn_flush.setGeometry(QtCore.QRect(20, 100, 271, 51))
        self.btn_flush.setObjectName("btn_flush")
        self.btn_confirm = QtWidgets.QPushButton(self.groupBox_4)
        self.btn_confirm.setGeometry(QtCore.QRect(20, 30, 271, 51))
        self.btn_confirm.setObjectName("btn_confirm")
        self.groupBox_5 = QtWidgets.QGroupBox(updateClass)
        self.groupBox_5.setGeometry(QtCore.QRect(330, 80, 301, 71))
        self.groupBox_5.setObjectName("groupBox_5")
        self.le_choose_name = QtWidgets.QLineEdit(self.groupBox_5)
        self.le_choose_name.setEnabled(False)
        self.le_choose_name.setGeometry(QtCore.QRect(10, 30, 61, 21))
        self.le_choose_name.setObjectName("le_choose_name")
        self.le_choose_phone = QtWidgets.QLineEdit(self.groupBox_5)
        self.le_choose_phone.setEnabled(False)
        self.le_choose_phone.setGeometry(QtCore.QRect(92, 30, 191, 21))
        self.le_choose_phone.setObjectName("le_choose_phone")

        self.retranslateUi(updateClass)
        QtCore.QMetaObject.connectSlotsByName(updateClass)

    def retranslateUi(self, updateClass):
        _translate = QtCore.QCoreApplication.translate
        updateClass.setWindowTitle(_translate("updateClass", "Dialog"))
        self.groupBox.setTitle(_translate("updateClass", "年份与周数"))
        self.label.setText(_translate("updateClass", "年份:"))
        self.cb_year.setItemText(0, _translate("updateClass", "未选择"))
        self.cb_year.setItemText(1, _translate("updateClass", "2019"))
        self.cb_year.setItemText(2, _translate("updateClass", "2020"))
        self.cb_year.setItemText(3, _translate("updateClass", "2021"))
        self.cb_year.setItemText(4, _translate("updateClass", "2022"))
        self.cb_year.setItemText(5, _translate("updateClass", "2023"))
        self.cb_year.setItemText(6, _translate("updateClass", "2024"))
        self.cb_year.setItemText(7, _translate("updateClass", "2025"))
        self.cb_year.setItemText(8, _translate("updateClass", "2026"))
        self.cb_year.setItemText(9, _translate("updateClass", "2027"))
        self.cb_year.setItemText(10, _translate("updateClass", "2028"))
        self.cb_year.setItemText(11, _translate("updateClass", "2029"))
        self.label_2.setText(_translate("updateClass", "周："))
        self.cb_week.setItemText(0, _translate("updateClass", "未选择"))
        self.cb_week.setItemText(1, _translate("updateClass", "1"))
        self.cb_week.setItemText(2, _translate("updateClass", "2"))
        self.cb_week.setItemText(3, _translate("updateClass", "3"))
        self.cb_week.setItemText(4, _translate("updateClass", "4"))
        self.cb_week.setItemText(5, _translate("updateClass", "5"))
        self.cb_week.setItemText(6, _translate("updateClass", "6"))
        self.cb_week.setItemText(7, _translate("updateClass", "7"))
        self.cb_week.setItemText(8, _translate("updateClass", "8"))
        self.cb_week.setItemText(9, _translate("updateClass", "9"))
        self.cb_week.setItemText(10, _translate("updateClass", "10"))
        self.groupBox_2.setTitle(_translate("updateClass", "当前周次未排课学生"))
        self.groupBox_3.setTitle(_translate("updateClass", "选择排课信息"))
        self.label_3.setText(_translate("updateClass", "选择教练："))
        self.label_4.setText(_translate("updateClass", "日期课时"))
        self.cb_coach.setItemText(0, _translate("updateClass", "未选择"))
        self.groupBox_4.setTitle(_translate("updateClass", "操作菜单"))
        self.btn_flush.setText(_translate("updateClass", "刷新未排课名单"))
        self.btn_confirm.setText(_translate("updateClass", "确认排课信息"))
        self.groupBox_5.setTitle(_translate("updateClass", "当前选中"))
