# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\waibao\updateClass.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_updateClass(object):
    def setupUi(self, updateClass):
        updateClass.setObjectName("updateClass")
        updateClass.resize(1291, 651)
        updateClass.setMinimumSize(QtCore.QSize(1291, 651))
        updateClass.setMaximumSize(QtCore.QSize(1291, 651))
        self.lb_head = QtWidgets.QLabel(updateClass)
        self.lb_head.setGeometry(QtCore.QRect(420, 30, 431, 41))
        self.lb_head.setStyleSheet("font: 75 28pt \"楷体\";")
        self.lb_head.setObjectName("lb_head")
        self.stackedWidget = QtWidgets.QStackedWidget(updateClass)
        self.stackedWidget.setGeometry(QtCore.QRect(140, 90, 1091, 511))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.groupBox_2 = QtWidgets.QGroupBox(self.page)
        self.groupBox_2.setGeometry(QtCore.QRect(40, 20, 221, 481))
        self.groupBox_2.setObjectName("groupBox_2")
        self.tv_show_mem = QtWidgets.QTableView(self.groupBox_2)
        self.tv_show_mem.setGeometry(QtCore.QRect(10, 20, 201, 451))
        self.tv_show_mem.setObjectName("tv_show_mem")
        self.groupBox_5 = QtWidgets.QGroupBox(self.page)
        self.groupBox_5.setGeometry(QtCore.QRect(270, 20, 251, 481))
        self.groupBox_5.setObjectName("groupBox_5")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_5)
        self.layoutWidget.setGeometry(QtCore.QRect(24, 30, 211, 421))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 0, 0, 1, 1)
        self.le_choose_name = QtWidgets.QLineEdit(self.layoutWidget)
        self.le_choose_name.setEnabled(False)
        self.le_choose_name.setObjectName("le_choose_name")
        self.gridLayout_3.addWidget(self.le_choose_name, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 1, 0, 1, 1)
        self.le_choose_gender = QtWidgets.QLineEdit(self.layoutWidget)
        self.le_choose_gender.setEnabled(False)
        self.le_choose_gender.setObjectName("le_choose_gender")
        self.gridLayout_3.addWidget(self.le_choose_gender, 1, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 2, 0, 1, 1)
        self.le_choose_parent = QtWidgets.QLineEdit(self.layoutWidget)
        self.le_choose_parent.setEnabled(False)
        self.le_choose_parent.setObjectName("le_choose_parent")
        self.gridLayout_3.addWidget(self.le_choose_parent, 2, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 3, 0, 1, 1)
        self.le_choose_phone = QtWidgets.QLineEdit(self.layoutWidget)
        self.le_choose_phone.setEnabled(False)
        self.le_choose_phone.setObjectName("le_choose_phone")
        self.gridLayout_3.addWidget(self.le_choose_phone, 3, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 4, 0, 1, 1)
        self.le_choose_type = QtWidgets.QLineEdit(self.layoutWidget)
        self.le_choose_type.setEnabled(False)
        self.le_choose_type.setObjectName("le_choose_type")
        self.gridLayout_3.addWidget(self.le_choose_type, 4, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 5, 0, 1, 1)
        self.le_choose_left = QtWidgets.QLineEdit(self.layoutWidget)
        self.le_choose_left.setEnabled(False)
        self.le_choose_left.setObjectName("le_choose_left")
        self.gridLayout_3.addWidget(self.le_choose_left, 5, 1, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.page)
        self.groupBox.setGeometry(QtCore.QRect(530, 20, 541, 61))
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 20, 521, 23))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.cb_week = QtWidgets.QComboBox(self.layoutWidget1)
        self.cb_week.setObjectName("cb_week")
        self.cb_week.addItem("")
        self.cb_week.addItem("")
        self.cb_week.addItem("")
        self.cb_week.addItem("")
        self.cb_week.addItem("")
        self.cb_week.addItem("")
        self.cb_week.addItem("")
        self.cb_week.addItem("")
        self.cb_week.addItem("")
        self.cb_week.addItem("")
        self.cb_week.addItem("")
        self.gridLayout.addWidget(self.cb_week, 0, 4, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 3, 1, 1)
        self.cb_year = QtWidgets.QComboBox(self.layoutWidget1)
        self.cb_year.setObjectName("cb_year")
        self.cb_year.addItem("")
        self.cb_year.addItem("")
        self.cb_year.addItem("")
        self.cb_year.addItem("")
        self.cb_year.addItem("")
        self.cb_year.addItem("")
        self.cb_year.addItem("")
        self.cb_year.addItem("")
        self.cb_year.addItem("")
        self.cb_year.addItem("")
        self.cb_year.addItem("")
        self.cb_year.addItem("")
        self.gridLayout.addWidget(self.cb_year, 0, 1, 1, 1)
        self.gridLayout.setColumnStretch(1, 1)
        self.gridLayout.setColumnStretch(4, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.page)
        self.groupBox_3.setGeometry(QtCore.QRect(530, 90, 541, 251))
        self.groupBox_3.setObjectName("groupBox_3")
        self.layoutWidget_2 = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 20, 521, 211))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
        self.cb_coach = QtWidgets.QComboBox(self.layoutWidget_2)
        self.cb_coach.setObjectName("cb_coach")
        self.cb_coach.addItem("")
        self.gridLayout_2.addWidget(self.cb_coach, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.tb_weekday = QtWidgets.QTabWidget(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tb_weekday.setFont(font)
        self.tb_weekday.setObjectName("tb_weekday")
        self.tb_mon = QtWidgets.QWidget()
        self.tb_mon.setObjectName("tb_mon")
        self.layoutWidget2 = QtWidgets.QWidget(self.tb_mon)
        self.layoutWidget2.setGeometry(QtCore.QRect(30, 10, 401, 131))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.layoutWidget2)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.cb_0 = QtWidgets.QCheckBox(self.layoutWidget2)
        self.cb_0.setObjectName("cb_0")
        self.gridLayout_5.addWidget(self.cb_0, 0, 0, 1, 1)
        self.cb_4 = QtWidgets.QCheckBox(self.layoutWidget2)
        self.cb_4.setObjectName("cb_4")
        self.gridLayout_5.addWidget(self.cb_4, 0, 1, 1, 1)
        self.cb_8 = QtWidgets.QCheckBox(self.layoutWidget2)
        self.cb_8.setObjectName("cb_8")
        self.gridLayout_5.addWidget(self.cb_8, 0, 2, 1, 1)
        self.cb_1 = QtWidgets.QCheckBox(self.layoutWidget2)
        self.cb_1.setObjectName("cb_1")
        self.gridLayout_5.addWidget(self.cb_1, 1, 0, 1, 1)
        self.cb_5 = QtWidgets.QCheckBox(self.layoutWidget2)
        self.cb_5.setObjectName("cb_5")
        self.gridLayout_5.addWidget(self.cb_5, 1, 1, 1, 1)
        self.cb_9 = QtWidgets.QCheckBox(self.layoutWidget2)
        self.cb_9.setObjectName("cb_9")
        self.gridLayout_5.addWidget(self.cb_9, 1, 2, 1, 1)
        self.cb_2 = QtWidgets.QCheckBox(self.layoutWidget2)
        self.cb_2.setObjectName("cb_2")
        self.gridLayout_5.addWidget(self.cb_2, 2, 0, 1, 1)
        self.cb_6 = QtWidgets.QCheckBox(self.layoutWidget2)
        self.cb_6.setObjectName("cb_6")
        self.gridLayout_5.addWidget(self.cb_6, 2, 1, 1, 1)
        self.cb_10 = QtWidgets.QCheckBox(self.layoutWidget2)
        self.cb_10.setObjectName("cb_10")
        self.gridLayout_5.addWidget(self.cb_10, 2, 2, 1, 1)
        self.cb_3 = QtWidgets.QCheckBox(self.layoutWidget2)
        self.cb_3.setObjectName("cb_3")
        self.gridLayout_5.addWidget(self.cb_3, 3, 0, 1, 1)
        self.cb_7 = QtWidgets.QCheckBox(self.layoutWidget2)
        self.cb_7.setObjectName("cb_7")
        self.gridLayout_5.addWidget(self.cb_7, 3, 1, 1, 1)
        self.cb_11 = QtWidgets.QCheckBox(self.layoutWidget2)
        self.cb_11.setObjectName("cb_11")
        self.gridLayout_5.addWidget(self.cb_11, 3, 2, 1, 1)
        self.tb_weekday.addTab(self.tb_mon, "")
        self.tb_tue = QtWidgets.QWidget()
        self.tb_tue.setObjectName("tb_tue")
        self.layoutWidget_4 = QtWidgets.QWidget(self.tb_tue)
        self.layoutWidget_4.setGeometry(QtCore.QRect(30, 10, 401, 131))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.layoutWidget_4)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.cb_12 = QtWidgets.QCheckBox(self.layoutWidget_4)
        self.cb_12.setObjectName("cb_12")
        self.gridLayout_6.addWidget(self.cb_12, 0, 0, 1, 1)
        self.cb_13 = QtWidgets.QCheckBox(self.layoutWidget_4)
        self.cb_13.setObjectName("cb_13")
        self.gridLayout_6.addWidget(self.cb_13, 0, 1, 1, 1)
        self.cb_14 = QtWidgets.QCheckBox(self.layoutWidget_4)
        self.cb_14.setObjectName("cb_14")
        self.gridLayout_6.addWidget(self.cb_14, 0, 2, 1, 1)
        self.cb_15 = QtWidgets.QCheckBox(self.layoutWidget_4)
        self.cb_15.setObjectName("cb_15")
        self.gridLayout_6.addWidget(self.cb_15, 1, 0, 1, 1)
        self.cb_16 = QtWidgets.QCheckBox(self.layoutWidget_4)
        self.cb_16.setObjectName("cb_16")
        self.gridLayout_6.addWidget(self.cb_16, 1, 1, 1, 1)
        self.cb_17 = QtWidgets.QCheckBox(self.layoutWidget_4)
        self.cb_17.setObjectName("cb_17")
        self.gridLayout_6.addWidget(self.cb_17, 1, 2, 1, 1)
        self.cb_18 = QtWidgets.QCheckBox(self.layoutWidget_4)
        self.cb_18.setObjectName("cb_18")
        self.gridLayout_6.addWidget(self.cb_18, 2, 0, 1, 1)
        self.cb_19 = QtWidgets.QCheckBox(self.layoutWidget_4)
        self.cb_19.setObjectName("cb_19")
        self.gridLayout_6.addWidget(self.cb_19, 2, 1, 1, 1)
        self.cb_20 = QtWidgets.QCheckBox(self.layoutWidget_4)
        self.cb_20.setObjectName("cb_20")
        self.gridLayout_6.addWidget(self.cb_20, 2, 2, 1, 1)
        self.cb_21 = QtWidgets.QCheckBox(self.layoutWidget_4)
        self.cb_21.setObjectName("cb_21")
        self.gridLayout_6.addWidget(self.cb_21, 3, 0, 1, 1)
        self.cb_22 = QtWidgets.QCheckBox(self.layoutWidget_4)
        self.cb_22.setObjectName("cb_22")
        self.gridLayout_6.addWidget(self.cb_22, 3, 1, 1, 1)
        self.cb_23 = QtWidgets.QCheckBox(self.layoutWidget_4)
        self.cb_23.setObjectName("cb_23")
        self.gridLayout_6.addWidget(self.cb_23, 3, 2, 1, 1)
        self.tb_weekday.addTab(self.tb_tue, "")
        self.tb_wed = QtWidgets.QWidget()
        self.tb_wed.setObjectName("tb_wed")
        self.layoutWidget_5 = QtWidgets.QWidget(self.tb_wed)
        self.layoutWidget_5.setGeometry(QtCore.QRect(30, 10, 401, 131))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.layoutWidget_5)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.cb_24 = QtWidgets.QCheckBox(self.layoutWidget_5)
        self.cb_24.setObjectName("cb_24")
        self.gridLayout_7.addWidget(self.cb_24, 0, 0, 1, 1)
        self.cb_25 = QtWidgets.QCheckBox(self.layoutWidget_5)
        self.cb_25.setObjectName("cb_25")
        self.gridLayout_7.addWidget(self.cb_25, 0, 1, 1, 1)
        self.cb_26 = QtWidgets.QCheckBox(self.layoutWidget_5)
        self.cb_26.setObjectName("cb_26")
        self.gridLayout_7.addWidget(self.cb_26, 0, 2, 1, 1)
        self.cb_27 = QtWidgets.QCheckBox(self.layoutWidget_5)
        self.cb_27.setObjectName("cb_27")
        self.gridLayout_7.addWidget(self.cb_27, 1, 0, 1, 1)
        self.cb_28 = QtWidgets.QCheckBox(self.layoutWidget_5)
        self.cb_28.setObjectName("cb_28")
        self.gridLayout_7.addWidget(self.cb_28, 1, 1, 1, 1)
        self.cb_29 = QtWidgets.QCheckBox(self.layoutWidget_5)
        self.cb_29.setObjectName("cb_29")
        self.gridLayout_7.addWidget(self.cb_29, 1, 2, 1, 1)
        self.cb_30 = QtWidgets.QCheckBox(self.layoutWidget_5)
        self.cb_30.setObjectName("cb_30")
        self.gridLayout_7.addWidget(self.cb_30, 2, 0, 1, 1)
        self.cb_31 = QtWidgets.QCheckBox(self.layoutWidget_5)
        self.cb_31.setObjectName("cb_31")
        self.gridLayout_7.addWidget(self.cb_31, 2, 1, 1, 1)
        self.cb_32 = QtWidgets.QCheckBox(self.layoutWidget_5)
        self.cb_32.setObjectName("cb_32")
        self.gridLayout_7.addWidget(self.cb_32, 2, 2, 1, 1)
        self.cb_33 = QtWidgets.QCheckBox(self.layoutWidget_5)
        self.cb_33.setObjectName("cb_33")
        self.gridLayout_7.addWidget(self.cb_33, 3, 0, 1, 1)
        self.cb_34 = QtWidgets.QCheckBox(self.layoutWidget_5)
        self.cb_34.setObjectName("cb_34")
        self.gridLayout_7.addWidget(self.cb_34, 3, 1, 1, 1)
        self.cb_35 = QtWidgets.QCheckBox(self.layoutWidget_5)
        self.cb_35.setObjectName("cb_35")
        self.gridLayout_7.addWidget(self.cb_35, 3, 2, 1, 1)
        self.tb_weekday.addTab(self.tb_wed, "")
        self.tb_thu = QtWidgets.QWidget()
        self.tb_thu.setObjectName("tb_thu")
        self.layoutWidget_6 = QtWidgets.QWidget(self.tb_thu)
        self.layoutWidget_6.setGeometry(QtCore.QRect(30, 10, 401, 131))
        self.layoutWidget_6.setObjectName("layoutWidget_6")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.layoutWidget_6)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.cb_36 = QtWidgets.QCheckBox(self.layoutWidget_6)
        self.cb_36.setObjectName("cb_36")
        self.gridLayout_8.addWidget(self.cb_36, 0, 0, 1, 1)
        self.cb_37 = QtWidgets.QCheckBox(self.layoutWidget_6)
        self.cb_37.setObjectName("cb_37")
        self.gridLayout_8.addWidget(self.cb_37, 0, 1, 1, 1)
        self.cb_38 = QtWidgets.QCheckBox(self.layoutWidget_6)
        self.cb_38.setObjectName("cb_38")
        self.gridLayout_8.addWidget(self.cb_38, 0, 2, 1, 1)
        self.cb_39 = QtWidgets.QCheckBox(self.layoutWidget_6)
        self.cb_39.setObjectName("cb_39")
        self.gridLayout_8.addWidget(self.cb_39, 1, 0, 1, 1)
        self.cb_40 = QtWidgets.QCheckBox(self.layoutWidget_6)
        self.cb_40.setObjectName("cb_40")
        self.gridLayout_8.addWidget(self.cb_40, 1, 1, 1, 1)
        self.cb_41 = QtWidgets.QCheckBox(self.layoutWidget_6)
        self.cb_41.setObjectName("cb_41")
        self.gridLayout_8.addWidget(self.cb_41, 1, 2, 1, 1)
        self.cb_42 = QtWidgets.QCheckBox(self.layoutWidget_6)
        self.cb_42.setObjectName("cb_42")
        self.gridLayout_8.addWidget(self.cb_42, 2, 0, 1, 1)
        self.cb_43 = QtWidgets.QCheckBox(self.layoutWidget_6)
        self.cb_43.setObjectName("cb_43")
        self.gridLayout_8.addWidget(self.cb_43, 2, 1, 1, 1)
        self.cb_44 = QtWidgets.QCheckBox(self.layoutWidget_6)
        self.cb_44.setObjectName("cb_44")
        self.gridLayout_8.addWidget(self.cb_44, 2, 2, 1, 1)
        self.cb_45 = QtWidgets.QCheckBox(self.layoutWidget_6)
        self.cb_45.setObjectName("cb_45")
        self.gridLayout_8.addWidget(self.cb_45, 3, 0, 1, 1)
        self.cb_46 = QtWidgets.QCheckBox(self.layoutWidget_6)
        self.cb_46.setObjectName("cb_46")
        self.gridLayout_8.addWidget(self.cb_46, 3, 1, 1, 1)
        self.cb_47 = QtWidgets.QCheckBox(self.layoutWidget_6)
        self.cb_47.setObjectName("cb_47")
        self.gridLayout_8.addWidget(self.cb_47, 3, 2, 1, 1)
        self.tb_weekday.addTab(self.tb_thu, "")
        self.tb_fri = QtWidgets.QWidget()
        self.tb_fri.setObjectName("tb_fri")
        self.layoutWidget_7 = QtWidgets.QWidget(self.tb_fri)
        self.layoutWidget_7.setGeometry(QtCore.QRect(30, 10, 401, 131))
        self.layoutWidget_7.setObjectName("layoutWidget_7")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.layoutWidget_7)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.cb_48 = QtWidgets.QCheckBox(self.layoutWidget_7)
        self.cb_48.setObjectName("cb_48")
        self.gridLayout_9.addWidget(self.cb_48, 0, 0, 1, 1)
        self.cb_49 = QtWidgets.QCheckBox(self.layoutWidget_7)
        self.cb_49.setObjectName("cb_49")
        self.gridLayout_9.addWidget(self.cb_49, 0, 1, 1, 1)
        self.cb_50 = QtWidgets.QCheckBox(self.layoutWidget_7)
        self.cb_50.setObjectName("cb_50")
        self.gridLayout_9.addWidget(self.cb_50, 0, 2, 1, 1)
        self.cb_51 = QtWidgets.QCheckBox(self.layoutWidget_7)
        self.cb_51.setObjectName("cb_51")
        self.gridLayout_9.addWidget(self.cb_51, 1, 0, 1, 1)
        self.cb_52 = QtWidgets.QCheckBox(self.layoutWidget_7)
        self.cb_52.setObjectName("cb_52")
        self.gridLayout_9.addWidget(self.cb_52, 1, 1, 1, 1)
        self.cb_53 = QtWidgets.QCheckBox(self.layoutWidget_7)
        self.cb_53.setObjectName("cb_53")
        self.gridLayout_9.addWidget(self.cb_53, 1, 2, 1, 1)
        self.cb_54 = QtWidgets.QCheckBox(self.layoutWidget_7)
        self.cb_54.setObjectName("cb_54")
        self.gridLayout_9.addWidget(self.cb_54, 2, 0, 1, 1)
        self.cb_55 = QtWidgets.QCheckBox(self.layoutWidget_7)
        self.cb_55.setObjectName("cb_55")
        self.gridLayout_9.addWidget(self.cb_55, 2, 1, 1, 1)
        self.cb_56 = QtWidgets.QCheckBox(self.layoutWidget_7)
        self.cb_56.setObjectName("cb_56")
        self.gridLayout_9.addWidget(self.cb_56, 2, 2, 1, 1)
        self.cb_57 = QtWidgets.QCheckBox(self.layoutWidget_7)
        self.cb_57.setObjectName("cb_57")
        self.gridLayout_9.addWidget(self.cb_57, 3, 0, 1, 1)
        self.cb_58 = QtWidgets.QCheckBox(self.layoutWidget_7)
        self.cb_58.setObjectName("cb_58")
        self.gridLayout_9.addWidget(self.cb_58, 3, 1, 1, 1)
        self.cb_59 = QtWidgets.QCheckBox(self.layoutWidget_7)
        self.cb_59.setObjectName("cb_59")
        self.gridLayout_9.addWidget(self.cb_59, 3, 2, 1, 1)
        self.tb_weekday.addTab(self.tb_fri, "")
        self.tb_sat = QtWidgets.QWidget()
        self.tb_sat.setObjectName("tb_sat")
        self.layoutWidget_8 = QtWidgets.QWidget(self.tb_sat)
        self.layoutWidget_8.setGeometry(QtCore.QRect(30, 10, 401, 131))
        self.layoutWidget_8.setObjectName("layoutWidget_8")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.layoutWidget_8)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.cb_60 = QtWidgets.QCheckBox(self.layoutWidget_8)
        self.cb_60.setObjectName("cb_60")
        self.gridLayout_10.addWidget(self.cb_60, 0, 0, 1, 1)
        self.cb_61 = QtWidgets.QCheckBox(self.layoutWidget_8)
        self.cb_61.setObjectName("cb_61")
        self.gridLayout_10.addWidget(self.cb_61, 0, 1, 1, 1)
        self.cb_62 = QtWidgets.QCheckBox(self.layoutWidget_8)
        self.cb_62.setObjectName("cb_62")
        self.gridLayout_10.addWidget(self.cb_62, 0, 2, 1, 1)
        self.cb_63 = QtWidgets.QCheckBox(self.layoutWidget_8)
        self.cb_63.setObjectName("cb_63")
        self.gridLayout_10.addWidget(self.cb_63, 1, 0, 1, 1)
        self.cb_64 = QtWidgets.QCheckBox(self.layoutWidget_8)
        self.cb_64.setObjectName("cb_64")
        self.gridLayout_10.addWidget(self.cb_64, 1, 1, 1, 1)
        self.cb_65 = QtWidgets.QCheckBox(self.layoutWidget_8)
        self.cb_65.setObjectName("cb_65")
        self.gridLayout_10.addWidget(self.cb_65, 1, 2, 1, 1)
        self.cb_66 = QtWidgets.QCheckBox(self.layoutWidget_8)
        self.cb_66.setObjectName("cb_66")
        self.gridLayout_10.addWidget(self.cb_66, 2, 0, 1, 1)
        self.cb_67 = QtWidgets.QCheckBox(self.layoutWidget_8)
        self.cb_67.setObjectName("cb_67")
        self.gridLayout_10.addWidget(self.cb_67, 2, 1, 1, 1)
        self.cb_68 = QtWidgets.QCheckBox(self.layoutWidget_8)
        self.cb_68.setObjectName("cb_68")
        self.gridLayout_10.addWidget(self.cb_68, 2, 2, 1, 1)
        self.cb_69 = QtWidgets.QCheckBox(self.layoutWidget_8)
        self.cb_69.setObjectName("cb_69")
        self.gridLayout_10.addWidget(self.cb_69, 3, 0, 1, 1)
        self.cb_70 = QtWidgets.QCheckBox(self.layoutWidget_8)
        self.cb_70.setObjectName("cb_70")
        self.gridLayout_10.addWidget(self.cb_70, 3, 1, 1, 1)
        self.cb_71 = QtWidgets.QCheckBox(self.layoutWidget_8)
        self.cb_71.setObjectName("cb_71")
        self.gridLayout_10.addWidget(self.cb_71, 3, 2, 1, 1)
        self.tb_weekday.addTab(self.tb_sat, "")
        self.tb_sun = QtWidgets.QWidget()
        self.tb_sun.setObjectName("tb_sun")
        self.layoutWidget_9 = QtWidgets.QWidget(self.tb_sun)
        self.layoutWidget_9.setGeometry(QtCore.QRect(30, 10, 401, 131))
        self.layoutWidget_9.setObjectName("layoutWidget_9")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.layoutWidget_9)
        self.gridLayout_11.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.cb_72 = QtWidgets.QCheckBox(self.layoutWidget_9)
        self.cb_72.setObjectName("cb_72")
        self.gridLayout_11.addWidget(self.cb_72, 0, 0, 1, 1)
        self.cb_73 = QtWidgets.QCheckBox(self.layoutWidget_9)
        self.cb_73.setObjectName("cb_73")
        self.gridLayout_11.addWidget(self.cb_73, 0, 1, 1, 1)
        self.cb_74 = QtWidgets.QCheckBox(self.layoutWidget_9)
        self.cb_74.setObjectName("cb_74")
        self.gridLayout_11.addWidget(self.cb_74, 0, 2, 1, 1)
        self.cb_75 = QtWidgets.QCheckBox(self.layoutWidget_9)
        self.cb_75.setObjectName("cb_75")
        self.gridLayout_11.addWidget(self.cb_75, 1, 0, 1, 1)
        self.cb_76 = QtWidgets.QCheckBox(self.layoutWidget_9)
        self.cb_76.setObjectName("cb_76")
        self.gridLayout_11.addWidget(self.cb_76, 1, 1, 1, 1)
        self.cb_77 = QtWidgets.QCheckBox(self.layoutWidget_9)
        self.cb_77.setObjectName("cb_77")
        self.gridLayout_11.addWidget(self.cb_77, 1, 2, 1, 1)
        self.cb_78 = QtWidgets.QCheckBox(self.layoutWidget_9)
        self.cb_78.setObjectName("cb_78")
        self.gridLayout_11.addWidget(self.cb_78, 2, 0, 1, 1)
        self.cb_79 = QtWidgets.QCheckBox(self.layoutWidget_9)
        self.cb_79.setObjectName("cb_79")
        self.gridLayout_11.addWidget(self.cb_79, 2, 1, 1, 1)
        self.cb_80 = QtWidgets.QCheckBox(self.layoutWidget_9)
        self.cb_80.setObjectName("cb_80")
        self.gridLayout_11.addWidget(self.cb_80, 2, 2, 1, 1)
        self.cb_81 = QtWidgets.QCheckBox(self.layoutWidget_9)
        self.cb_81.setObjectName("cb_81")
        self.gridLayout_11.addWidget(self.cb_81, 3, 0, 1, 1)
        self.cb_82 = QtWidgets.QCheckBox(self.layoutWidget_9)
        self.cb_82.setObjectName("cb_82")
        self.gridLayout_11.addWidget(self.cb_82, 3, 1, 1, 1)
        self.cb_83 = QtWidgets.QCheckBox(self.layoutWidget_9)
        self.cb_83.setObjectName("cb_83")
        self.gridLayout_11.addWidget(self.cb_83, 3, 2, 1, 1)
        self.tb_weekday.addTab(self.tb_sun, "")
        self.gridLayout_2.addWidget(self.tb_weekday, 1, 1, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.page)
        self.groupBox_4.setGeometry(QtCore.QRect(530, 360, 541, 141))
        self.groupBox_4.setObjectName("groupBox_4")
        self.btn_flush = QtWidgets.QPushButton(self.groupBox_4)
        self.btn_flush.setGeometry(QtCore.QRect(280, 40, 221, 71))
        self.btn_flush.setObjectName("btn_flush")
        self.btn_confirm = QtWidgets.QPushButton(self.groupBox_4)
        self.btn_confirm.setGeometry(QtCore.QRect(40, 40, 211, 71))
        self.btn_confirm.setObjectName("btn_confirm")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.groupBox_6 = QtWidgets.QGroupBox(self.page_2)
        self.groupBox_6.setGeometry(QtCore.QRect(570, 30, 391, 61))
        self.groupBox_6.setObjectName("groupBox_6")
        self.layoutWidget_3 = QtWidgets.QWidget(self.groupBox_6)
        self.layoutWidget_3.setGeometry(QtCore.QRect(10, 20, 371, 23))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.layoutWidget_3)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.cb_week_2 = QtWidgets.QComboBox(self.layoutWidget_3)
        self.cb_week_2.setObjectName("cb_week_2")
        self.cb_week_2.addItem("")
        self.cb_week_2.addItem("")
        self.cb_week_2.addItem("")
        self.cb_week_2.addItem("")
        self.cb_week_2.addItem("")
        self.cb_week_2.addItem("")
        self.cb_week_2.addItem("")
        self.cb_week_2.addItem("")
        self.cb_week_2.addItem("")
        self.cb_week_2.addItem("")
        self.cb_week_2.addItem("")
        self.gridLayout_4.addWidget(self.cb_week_2, 0, 4, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_11.setObjectName("label_11")
        self.gridLayout_4.addWidget(self.label_11, 0, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_12.setObjectName("label_12")
        self.gridLayout_4.addWidget(self.label_12, 0, 3, 1, 1)
        self.cb_year_2 = QtWidgets.QComboBox(self.layoutWidget_3)
        self.cb_year_2.setObjectName("cb_year_2")
        self.cb_year_2.addItem("")
        self.cb_year_2.addItem("")
        self.cb_year_2.addItem("")
        self.cb_year_2.addItem("")
        self.cb_year_2.addItem("")
        self.cb_year_2.addItem("")
        self.cb_year_2.addItem("")
        self.cb_year_2.addItem("")
        self.cb_year_2.addItem("")
        self.cb_year_2.addItem("")
        self.cb_year_2.addItem("")
        self.cb_year_2.addItem("")
        self.gridLayout_4.addWidget(self.cb_year_2, 0, 1, 1, 1)
        self.gridLayout_4.setColumnStretch(1, 1)
        self.gridLayout_4.setColumnStretch(4, 1)
        self.stackedWidget.addWidget(self.page_2)
        self.left_widget = QtWidgets.QWidget(updateClass)
        self.left_widget.setGeometry(QtCore.QRect(0, 0, 161, 661))
        self.left_widget.setStyleSheet("background:#DDDDDD")
        self.left_widget.setObjectName("left_widget")
        self.listFunc = QtWidgets.QListWidget(self.left_widget)
        self.listFunc.setGeometry(QtCore.QRect(10, 60, 131, 441))
        self.listFunc.setStyleSheet("QListWidget#listFunc{\n"
"    outline: 0px;\n"
"    border:0px;\n"
"    min-width: 120px;\n"
"    color: Black;\n"
"    background: #DDDDDD;\n"
"}\n"
"\n"
"QListWidget#listFunc::Item{\n"
"     height:30px;\n"
"}\n"
"QListWidget#listFunc::Item:selected {\n"
"    background: rgb(49, 194, 124);\n"
"    border-radius:1.5px;\n"
"   \n"
"}\n"
"")
        self.listFunc.setObjectName("listFunc")
        item = QtWidgets.QListWidgetItem()
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("resource/calender.svg"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        item.setIcon(icon)
        self.listFunc.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("resource/update.svg"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        item.setIcon(icon1)
        self.listFunc.addItem(item)
        self.label_13 = QtWidgets.QLabel(self.left_widget)
        self.label_13.setGeometry(QtCore.QRect(40, 20, 81, 21))
        self.label_13.setStyleSheet("font: 75 14pt \"黑体\";")
        self.label_13.setObjectName("label_13")

        self.retranslateUi(updateClass)
        self.stackedWidget.setCurrentIndex(0)
        self.tb_weekday.setCurrentIndex(6)
        QtCore.QMetaObject.connectSlotsByName(updateClass)

    def retranslateUi(self, updateClass):
        _translate = QtCore.QCoreApplication.translate
        updateClass.setWindowTitle(_translate("updateClass", "Dialog"))
        self.lb_head.setText(_translate("updateClass", "学 员 排 课 系 统"))
        self.groupBox_2.setTitle(_translate("updateClass", "当前周次未排课学生"))
        self.groupBox_5.setTitle(_translate("updateClass", "当前选中"))
        self.label_5.setText(_translate("updateClass", "姓名："))
        self.label_7.setText(_translate("updateClass", "性别："))
        self.label_10.setText(_translate("updateClass", "家长："))
        self.label_6.setText(_translate("updateClass", "联系方式："))
        self.label_8.setText(_translate("updateClass", "办卡模式："))
        self.label_9.setText(_translate("updateClass", "课时次数："))
        self.groupBox.setTitle(_translate("updateClass", "年份与周数"))
        self.cb_week.setItemText(0, _translate("updateClass", "未选择"))
        self.cb_week.setItemText(1, _translate("updateClass", "1"))
        self.cb_week.setItemText(2, _translate("updateClass", "2"))
        self.cb_week.setItemText(3, _translate("updateClass", "3"))
        self.cb_week.setItemText(4, _translate("updateClass", "4"))
        self.cb_week.setItemText(5, _translate("updateClass", "5"))
        self.cb_week.setItemText(6, _translate("updateClass", "6"))
        self.cb_week.setItemText(7, _translate("updateClass", "7"))
        self.cb_week.setItemText(8, _translate("updateClass", "8"))
        self.cb_week.setItemText(9, _translate("updateClass", "9"))
        self.cb_week.setItemText(10, _translate("updateClass", "10"))
        self.label.setText(_translate("updateClass", "年份:"))
        self.label_2.setText(_translate("updateClass", "周："))
        self.cb_year.setItemText(0, _translate("updateClass", "未选择"))
        self.cb_year.setItemText(1, _translate("updateClass", "2019"))
        self.cb_year.setItemText(2, _translate("updateClass", "2020"))
        self.cb_year.setItemText(3, _translate("updateClass", "2021"))
        self.cb_year.setItemText(4, _translate("updateClass", "2022"))
        self.cb_year.setItemText(5, _translate("updateClass", "2023"))
        self.cb_year.setItemText(6, _translate("updateClass", "2024"))
        self.cb_year.setItemText(7, _translate("updateClass", "2025"))
        self.cb_year.setItemText(8, _translate("updateClass", "2026"))
        self.cb_year.setItemText(9, _translate("updateClass", "2027"))
        self.cb_year.setItemText(10, _translate("updateClass", "2028"))
        self.cb_year.setItemText(11, _translate("updateClass", "2029"))
        self.groupBox_3.setTitle(_translate("updateClass", "选择排课信息"))
        self.label_4.setText(_translate("updateClass", "日期课时："))
        self.cb_coach.setItemText(0, _translate("updateClass", "未选择"))
        self.label_3.setText(_translate("updateClass", "选择教练："))
        self.cb_0.setText(_translate("updateClass", "10:00"))
        self.cb_4.setText(_translate("updateClass", "14:00"))
        self.cb_8.setText(_translate("updateClass", "18:00"))
        self.cb_1.setText(_translate("updateClass", "11:00"))
        self.cb_5.setText(_translate("updateClass", "15:00"))
        self.cb_9.setText(_translate("updateClass", "19:00"))
        self.cb_2.setText(_translate("updateClass", "12:00"))
        self.cb_6.setText(_translate("updateClass", "16:00"))
        self.cb_10.setText(_translate("updateClass", "20:00"))
        self.cb_3.setText(_translate("updateClass", "13:00"))
        self.cb_7.setText(_translate("updateClass", "17:00"))
        self.cb_11.setText(_translate("updateClass", "21:00"))
        self.tb_weekday.setTabText(self.tb_weekday.indexOf(self.tb_mon), _translate("updateClass", "周一"))
        self.cb_12.setText(_translate("updateClass", "10:00"))
        self.cb_13.setText(_translate("updateClass", "14:00"))
        self.cb_14.setText(_translate("updateClass", "18:00"))
        self.cb_15.setText(_translate("updateClass", "11:00"))
        self.cb_16.setText(_translate("updateClass", "15:00"))
        self.cb_17.setText(_translate("updateClass", "19:00"))
        self.cb_18.setText(_translate("updateClass", "12:00"))
        self.cb_19.setText(_translate("updateClass", "16:00"))
        self.cb_20.setText(_translate("updateClass", "20:00"))
        self.cb_21.setText(_translate("updateClass", "13:00"))
        self.cb_22.setText(_translate("updateClass", "17:00"))
        self.cb_23.setText(_translate("updateClass", "21:00"))
        self.tb_weekday.setTabText(self.tb_weekday.indexOf(self.tb_tue), _translate("updateClass", "周二"))
        self.cb_24.setText(_translate("updateClass", "10:00"))
        self.cb_25.setText(_translate("updateClass", "14:00"))
        self.cb_26.setText(_translate("updateClass", "18:00"))
        self.cb_27.setText(_translate("updateClass", "11:00"))
        self.cb_28.setText(_translate("updateClass", "15:00"))
        self.cb_29.setText(_translate("updateClass", "19:00"))
        self.cb_30.setText(_translate("updateClass", "12:00"))
        self.cb_31.setText(_translate("updateClass", "16:00"))
        self.cb_32.setText(_translate("updateClass", "20:00"))
        self.cb_33.setText(_translate("updateClass", "13:00"))
        self.cb_34.setText(_translate("updateClass", "17:00"))
        self.cb_35.setText(_translate("updateClass", "21:00"))
        self.tb_weekday.setTabText(self.tb_weekday.indexOf(self.tb_wed), _translate("updateClass", "周三"))
        self.cb_36.setText(_translate("updateClass", "10:00"))
        self.cb_37.setText(_translate("updateClass", "14:00"))
        self.cb_38.setText(_translate("updateClass", "18:00"))
        self.cb_39.setText(_translate("updateClass", "11:00"))
        self.cb_40.setText(_translate("updateClass", "15:00"))
        self.cb_41.setText(_translate("updateClass", "19:00"))
        self.cb_42.setText(_translate("updateClass", "12:00"))
        self.cb_43.setText(_translate("updateClass", "16:00"))
        self.cb_44.setText(_translate("updateClass", "20:00"))
        self.cb_45.setText(_translate("updateClass", "13:00"))
        self.cb_46.setText(_translate("updateClass", "17:00"))
        self.cb_47.setText(_translate("updateClass", "21:00"))
        self.tb_weekday.setTabText(self.tb_weekday.indexOf(self.tb_thu), _translate("updateClass", "周四"))
        self.cb_48.setText(_translate("updateClass", "10:00"))
        self.cb_49.setText(_translate("updateClass", "14:00"))
        self.cb_50.setText(_translate("updateClass", "18:00"))
        self.cb_51.setText(_translate("updateClass", "11:00"))
        self.cb_52.setText(_translate("updateClass", "15:00"))
        self.cb_53.setText(_translate("updateClass", "19:00"))
        self.cb_54.setText(_translate("updateClass", "12:00"))
        self.cb_55.setText(_translate("updateClass", "16:00"))
        self.cb_56.setText(_translate("updateClass", "20:00"))
        self.cb_57.setText(_translate("updateClass", "13:00"))
        self.cb_58.setText(_translate("updateClass", "17:00"))
        self.cb_59.setText(_translate("updateClass", "21:00"))
        self.tb_weekday.setTabText(self.tb_weekday.indexOf(self.tb_fri), _translate("updateClass", "周五"))
        self.cb_60.setText(_translate("updateClass", "10:00"))
        self.cb_61.setText(_translate("updateClass", "14:00"))
        self.cb_62.setText(_translate("updateClass", "18:00"))
        self.cb_63.setText(_translate("updateClass", "11:00"))
        self.cb_64.setText(_translate("updateClass", "15:00"))
        self.cb_65.setText(_translate("updateClass", "19:00"))
        self.cb_66.setText(_translate("updateClass", "12:00"))
        self.cb_67.setText(_translate("updateClass", "16:00"))
        self.cb_68.setText(_translate("updateClass", "20:00"))
        self.cb_69.setText(_translate("updateClass", "13:00"))
        self.cb_70.setText(_translate("updateClass", "17:00"))
        self.cb_71.setText(_translate("updateClass", "21:00"))
        self.tb_weekday.setTabText(self.tb_weekday.indexOf(self.tb_sat), _translate("updateClass", "周六"))
        self.cb_72.setText(_translate("updateClass", "10:00"))
        self.cb_73.setText(_translate("updateClass", "14:00"))
        self.cb_74.setText(_translate("updateClass", "18:00"))
        self.cb_75.setText(_translate("updateClass", "11:00"))
        self.cb_76.setText(_translate("updateClass", "15:00"))
        self.cb_77.setText(_translate("updateClass", "19:00"))
        self.cb_78.setText(_translate("updateClass", "12:00"))
        self.cb_79.setText(_translate("updateClass", "16:00"))
        self.cb_80.setText(_translate("updateClass", "20:00"))
        self.cb_81.setText(_translate("updateClass", "13:00"))
        self.cb_82.setText(_translate("updateClass", "17:00"))
        self.cb_83.setText(_translate("updateClass", "21:00"))
        self.tb_weekday.setTabText(self.tb_weekday.indexOf(self.tb_sun), _translate("updateClass", "周日"))
        self.groupBox_4.setTitle(_translate("updateClass", "操作菜单"))
        self.btn_flush.setText(_translate("updateClass", "刷新未排课名单"))
        self.btn_confirm.setText(_translate("updateClass", "确认排课信息"))
        self.groupBox_6.setTitle(_translate("updateClass", "年份与周数"))
        self.cb_week_2.setItemText(0, _translate("updateClass", "未选择"))
        self.cb_week_2.setItemText(1, _translate("updateClass", "1"))
        self.cb_week_2.setItemText(2, _translate("updateClass", "2"))
        self.cb_week_2.setItemText(3, _translate("updateClass", "3"))
        self.cb_week_2.setItemText(4, _translate("updateClass", "4"))
        self.cb_week_2.setItemText(5, _translate("updateClass", "5"))
        self.cb_week_2.setItemText(6, _translate("updateClass", "6"))
        self.cb_week_2.setItemText(7, _translate("updateClass", "7"))
        self.cb_week_2.setItemText(8, _translate("updateClass", "8"))
        self.cb_week_2.setItemText(9, _translate("updateClass", "9"))
        self.cb_week_2.setItemText(10, _translate("updateClass", "10"))
        self.label_11.setText(_translate("updateClass", "年份:"))
        self.label_12.setText(_translate("updateClass", "周："))
        self.cb_year_2.setItemText(0, _translate("updateClass", "未选择"))
        self.cb_year_2.setItemText(1, _translate("updateClass", "2019"))
        self.cb_year_2.setItemText(2, _translate("updateClass", "2020"))
        self.cb_year_2.setItemText(3, _translate("updateClass", "2021"))
        self.cb_year_2.setItemText(4, _translate("updateClass", "2022"))
        self.cb_year_2.setItemText(5, _translate("updateClass", "2023"))
        self.cb_year_2.setItemText(6, _translate("updateClass", "2024"))
        self.cb_year_2.setItemText(7, _translate("updateClass", "2025"))
        self.cb_year_2.setItemText(8, _translate("updateClass", "2026"))
        self.cb_year_2.setItemText(9, _translate("updateClass", "2027"))
        self.cb_year_2.setItemText(10, _translate("updateClass", "2028"))
        self.cb_year_2.setItemText(11, _translate("updateClass", "2029"))
        __sortingEnabled = self.listFunc.isSortingEnabled()
        self.listFunc.setSortingEnabled(False)
        item = self.listFunc.item(0)
        item.setText(_translate("updateClass", "按照周次排课"))
        item = self.listFunc.item(1)
        item.setText(_translate("updateClass", "更新排课信息"))
        self.listFunc.setSortingEnabled(__sortingEnabled)
        self.label_13.setText(_translate("updateClass", "菜单栏"))
