# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\waibaoTest\GoodsSystem\sysgoods.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_sysGoods(object):
    def setupUi(self, sysGoods):
        sysGoods.setObjectName("sysGoods")
        sysGoods.resize(1291, 651)
        sysGoods.setMinimumSize(QtCore.QSize(1291, 651))
        sysGoods.setMaximumSize(QtCore.QSize(1291, 651))
        self.left_widget = QtWidgets.QWidget(sysGoods)
        self.left_widget.setGeometry(QtCore.QRect(0, 0, 171, 661))
        self.left_widget.setStyleSheet("background:#DDDDDD")
        self.left_widget.setObjectName("left_widget")
        self.listFunc = QtWidgets.QListWidget(self.left_widget)
        self.listFunc.setGeometry(QtCore.QRect(20, 60, 131, 441))
        self.listFunc.setStyleSheet("QListWidget#listFunc{\n"
"    outline: 0px;\n"
"    border:0px;\n"
"    min-width: 120px;\n"
"    color: Black;\n"
"    background: #DDDDDD;\n"
"}\n"
"\n"
"QListWidget#listFunc::Item{\n"
"     height:30px;\n"
"}\n"
"QListWidget#listFunc::Item:selected {\n"
"    background: rgb(49, 194, 124);\n"
"    border-radius:1.5px;\n"
"   \n"
"}\n"
"")
        self.listFunc.setObjectName("listFunc")
        item = QtWidgets.QListWidgetItem()
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("resource/goods_inout.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon)
        self.listFunc.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("resource/goods.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon1)
        self.listFunc.addItem(item)
        self.label = QtWidgets.QLabel(self.left_widget)
        self.label.setGeometry(QtCore.QRect(40, 20, 81, 21))
        self.label.setStyleSheet("font: 75 14pt \"黑体\";")
        self.label.setObjectName("label")
        self.lb_head = QtWidgets.QLabel(sysGoods)
        self.lb_head.setGeometry(QtCore.QRect(550, 20, 281, 41))
        self.lb_head.setStyleSheet("font: 75 28pt \"楷体\";")
        self.lb_head.setObjectName("lb_head")
        self.stackedWidget = QtWidgets.QStackedWidget(sysGoods)
        self.stackedWidget.setGeometry(QtCore.QRect(210, 80, 1061, 561))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.label_3 = QtWidgets.QLabel(self.page_2)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 141, 31))
        self.label_3.setStyleSheet("font: 75 14pt \"黑体\";")
        self.label_3.setObjectName("label_3")
        self.widget = QtWidgets.QWidget(self.page_2)
        self.widget.setGeometry(QtCore.QRect(231, 91, 461, 311))
        self.widget.setObjectName("widget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.cb_inout_month = QtWidgets.QComboBox(self.widget)
        self.cb_inout_month.setObjectName("cb_inout_month")
        self.gridLayout_3.addWidget(self.cb_inout_month, 4, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 1, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.widget)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 4, 4, 1, 1)
        self.cb_inout_year = QtWidgets.QComboBox(self.widget)
        self.cb_inout_year.setObjectName("cb_inout_year")
        self.gridLayout_3.addWidget(self.cb_inout_year, 4, 1, 1, 1)
        self.le_inout_name = QtWidgets.QLineEdit(self.widget)
        self.le_inout_name.setObjectName("le_inout_name")
        self.gridLayout_3.addWidget(self.le_inout_name, 0, 1, 1, 6)
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 4, 0, 1, 1)
        self.cb_inout_day = QtWidgets.QComboBox(self.widget)
        self.cb_inout_day.setObjectName("cb_inout_day")
        self.gridLayout_3.addWidget(self.cb_inout_day, 4, 5, 1, 1)
        self.btn_inout_confirm = QtWidgets.QPushButton(self.widget)
        self.btn_inout_confirm.setObjectName("btn_inout_confirm")
        self.gridLayout_3.addWidget(self.btn_inout_confirm, 6, 0, 1, 7)
        self.cb_inout = QtWidgets.QComboBox(self.widget)
        self.cb_inout.setObjectName("cb_inout")
        self.cb_inout.addItem("")
        self.cb_inout.addItem("")
        self.gridLayout_3.addWidget(self.cb_inout, 1, 1, 1, 6)
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 4, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.widget)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 4, 6, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 2, 0, 1, 1)
        self.le_inout_price = QtWidgets.QLineEdit(self.widget)
        self.le_inout_price.setObjectName("le_inout_price")
        self.gridLayout_3.addWidget(self.le_inout_price, 2, 1, 1, 6)
        self.label_13 = QtWidgets.QLabel(self.widget)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 0, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.widget)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 3, 0, 1, 1)
        self.le_inout_num = QtWidgets.QLineEdit(self.widget)
        self.le_inout_num.setObjectName("le_inout_num")
        self.gridLayout_3.addWidget(self.le_inout_num, 3, 1, 1, 6)
        self.stackedWidget.addWidget(self.page_2)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.label_2 = QtWidgets.QLabel(self.page)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 141, 31))
        self.label_2.setStyleSheet("font: 75 14pt \"黑体\";")
        self.label_2.setObjectName("label_2")
        self.tv_goods = QtWidgets.QTableView(self.page)
        self.tv_goods.setGeometry(QtCore.QRect(60, 130, 641, 401))
        self.tv_goods.setObjectName("tv_goods")
        self.btn_flush = QtWidgets.QPushButton(self.page)
        self.btn_flush.setGeometry(QtCore.QRect(60, 50, 921, 28))
        self.btn_flush.setObjectName("btn_flush")
        self.groupBox = QtWidgets.QGroupBox(self.page)
        self.groupBox.setGeometry(QtCore.QRect(710, 130, 271, 401))
        self.groupBox.setObjectName("groupBox")
        self.btn_confirm_add = QtWidgets.QPushButton(self.groupBox)
        self.btn_confirm_add.setGeometry(QtCore.QRect(20, 347, 241, 41))
        self.btn_confirm_add.setObjectName("btn_confirm_add")
        self.widget1 = QtWidgets.QWidget(self.groupBox)
        self.widget1.setGeometry(QtCore.QRect(20, 20, 241, 321))
        self.widget1.setObjectName("widget1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget1)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_4 = QtWidgets.QLabel(self.widget1)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.widget1)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 1, 0, 1, 1)
        self.te_goods_info = QtWidgets.QTextEdit(self.widget1)
        self.te_goods_info.setObjectName("te_goods_info")
        self.gridLayout_2.addWidget(self.te_goods_info, 1, 1, 1, 1)
        self.le_goods_name = QtWidgets.QLineEdit(self.widget1)
        self.le_goods_name.setObjectName("le_goods_name")
        self.gridLayout_2.addWidget(self.le_goods_name, 0, 1, 1, 1)
        self.widget2 = QtWidgets.QWidget(self.page)
        self.widget2.setGeometry(QtCore.QRect(60, 90, 921, 30))
        self.widget2.setObjectName("widget2")
        self.gridLayout = QtWidgets.QGridLayout(self.widget2)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.btn_remove_select = QtWidgets.QPushButton(self.widget2)
        self.btn_remove_select.setObjectName("btn_remove_select")
        self.gridLayout.addWidget(self.btn_remove_select, 0, 0, 1, 1)
        self.le_filter = QtWidgets.QLineEdit(self.widget2)
        self.le_filter.setObjectName("le_filter")
        self.gridLayout.addWidget(self.le_filter, 0, 1, 1, 1)
        self.stackedWidget.addWidget(self.page)

        self.retranslateUi(sysGoods)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(sysGoods)

    def retranslateUi(self, sysGoods):
        _translate = QtCore.QCoreApplication.translate
        sysGoods.setWindowTitle(_translate("sysGoods", "仓库系统"))
        __sortingEnabled = self.listFunc.isSortingEnabled()
        self.listFunc.setSortingEnabled(False)
        item = self.listFunc.item(0)
        item.setText(_translate("sysGoods", "进/出库登记"))
        item = self.listFunc.item(1)
        item.setText(_translate("sysGoods", "货物增/删/查"))
        self.listFunc.setSortingEnabled(__sortingEnabled)
        self.label.setText(_translate("sysGoods", "菜单栏"))
        self.lb_head.setText(_translate("sysGoods", "仓 库 系 统"))
        self.label_3.setText(_translate("sysGoods", "进/出库登记"))
        self.label_6.setText(_translate("sysGoods", "进/出库："))
        self.label_10.setText(_translate("sysGoods", "月"))
        self.label_8.setText(_translate("sysGoods", "进/出库日期："))
        self.btn_inout_confirm.setText(_translate("sysGoods", "登记确认"))
        self.cb_inout.setItemText(0, _translate("sysGoods", "进库"))
        self.cb_inout.setItemText(1, _translate("sysGoods", "出库"))
        self.label_9.setText(_translate("sysGoods", "年"))
        self.label_11.setText(_translate("sysGoods", "日"))
        self.label_7.setText(_translate("sysGoods", "进/出库价格："))
        self.label_13.setText(_translate("sysGoods", "货物名："))
        self.label_12.setText(_translate("sysGoods", "进/出库数目："))
        self.label_2.setText(_translate("sysGoods", "货物增/删/查"))
        self.btn_flush.setText(_translate("sysGoods", "连接数据库获取仓库货物信息"))
        self.groupBox.setTitle(_translate("sysGoods", "添加货物"))
        self.btn_confirm_add.setText(_translate("sysGoods", "确认添加"))
        self.label_4.setText(_translate("sysGoods", "货物名："))
        self.label_5.setText(_translate("sysGoods", "货物简介:"))
        self.btn_remove_select.setText(_translate("sysGoods", "删除选中货物"))
        self.le_filter.setPlaceholderText(_translate("sysGoods", "键入货物名关键词以过滤货物"))
